cp ChangeLog                                                        \users\jum002\Documents\GitHub\ADT
cp config.h                                                         \users\jum002\Documents\GitHub\ADT
cp configure.ac                                                     \users\jum002\Documents\GitHub\ADT
cp COPYING                                                          \users\jum002\Documents\GitHub\ADT
cp exclude.txt                                                      \users\jum002\Documents\GitHub\ADT
cp gitsync.bat                                                      \users\jum002\Documents\GitHub\ADT
cp init_config.sh                                                   \users\jum002\Documents\GitHub\ADT
cp INSTALL                                                          \users\jum002\Documents\GitHub\ADT
cp Makefile.am                                                      \users\jum002\Documents\GitHub\ADT
cp README                                                           \users\jum002\Documents\GitHub\ADT
cp WinInstall32.iss                                                 \users\jum002\Documents\GitHub\ADT
cp WinInstall64.iss                                                 \users\jum002\Documents\GitHub\ADT
cp ylwrap                                                           \users\jum002\Documents\GitHub\ADT
cp Doc\ADT.layout                                                   \users\jum002\Documents\GitHub\ADT\Doc
cp Doc\Presentation                                                 \users\jum002\Documents\GitHub\ADT\Doc
cp Doc\users-manual.lyx                                             \users\jum002\Documents\GitHub\ADT\Doc
cp Doc\users-manual.pdf                                             \users\jum002\Documents\GitHub\ADT\Doc
cp Doc\Presentation\ADT-flowchart.png                               \users\jum002\Documents\GitHub\ADT\Doc\Presentation
cp Doc\Presentation\presentation.html                               \users\jum002\Documents\GitHub\ADT\Doc\Presentation
cp objs\ADLib.vcxproj                                               \users\jum002\Documents\GitHub\ADT\objs
cp objs\ADLibErr.vcxproj                                            \users\jum002\Documents\GitHub\ADT\objs
cp objs\ADLibR.vcxproj                                              \users\jum002\Documents\GitHub\ADT\objs
cp objs\ADLibTest.vcxproj                                           \users\jum002\Documents\GitHub\ADT\objs
cp objs\fdlibm-5.2.vcxproj                                          \users\jum002\Documents\GitHub\ADT\objs
cp objs\adt.sdf                                                     \users\jum002\Documents\GitHub\ADT\objs
cp objs\adt.sln                                                     \users\jum002\Documents\GitHub\ADT\objs
cp objs\Makefile.am                                                 \users\jum002\Documents\GitHub\ADT\objs
cp objs\ADLib\Makefile.am                                           \users\jum002\Documents\GitHub\ADT\objs\ADLib
cp objs\ADLibPascal\Windows\Win32\build_lib.bat                     \users\jum002\Documents\GitHub\ADT\objs\ADLibPascal\Windows\Win32
cp objs\ADLibPascal\Windows\x64\build_lib.bat                       \users\jum002\Documents\GitHub\ADT\objs\ADLibPascal\Windows\x64
cp objs\ADLibTest\Makefile.am                                       \users\jum002\Documents\GitHub\ADT\objs\ADLibTest
cp objs\blackbox_parse\Makefile.am                                  \users\jum002\Documents\GitHub\ADT\objs\blackbox_parse
cp objs\cpp_parse\Makefile.am                                       \users\jum002\Documents\GitHub\ADT\objs\cpp_parse
cp objs\delphi_parse\Makefile.am                                    \users\jum002\Documents\GitHub\ADT\objs\delphi_parse
cp objs\expression_parse\Makefile.am                                \users\jum002\Documents\GitHub\ADT\objs\expression_parse
cp objs\fortran_parse\Makefile.am                                   \users\jum002\Documents\GitHub\ADT\objs\fortran_parse
cp objs\java_parse\Makefile.am                                      \users\jum002\Documents\GitHub\ADT\objs\java_parse
cp objs\make_parse\Makefile.am                                      \users\jum002\Documents\GitHub\ADT\objs\make_parse
cp objs\sample\ArrayTest\Makefile.am                                \users\jum002\Documents\GitHub\ADT\objs\sample\ArrayTest
cp objs\sample\Mseom\Makefile.am                                    \users\jum002\Documents\GitHub\ADT\objs\sample\Mseom
cp objs\sample\Rosenbrock\Makefile.am                               \users\jum002\Documents\GitHub\ADT\objs\sample\Rosenbrock
cp sample\ArrayTest\build_lib.bat                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest.bbdef                                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest.cpp                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest.hpp                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest.lpi                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest.mk                                    \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest.R                                     \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest.vcxproj                               \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest_registration.cpp                      \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTest_Unit.pas                              \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTestPas.lpr                                \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTestPas.mk                                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\ArrayTestPas.R                                  \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\AT_R_interface.r                                \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\build_lib.sh                                    \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\run_mk                                          \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
cp sample\ArrayTest\include\AT_array_plans.hpp                      \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_array_plans_copy.hpp                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_array_plans_init.hpp                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_constructor_args.hpp                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_constructor_arrays_phase_1.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_constructor_call_args.hpp            \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_constructor_locals.hpp               \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_constructor_scalars_phase_1.hpp      \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_decl_lib_interface_constructor.hpp   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_decl_lib_interface_globals.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_decl_lib_interface_methods.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_impl_lib_interface_constructor.hpp   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_impl_lib_interface_globals.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_impl_lib_interface_methods.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\ArrayTest\include\AT_impl_lib_registration.hpp            \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
cp sample\include\common.bbdef                                      \users\jum002\Documents\GitHub\ADT\sample\common
cp sample\include\cpp_macros.txt                                    \users\jum002\Documents\GitHub\ADT\sample\common
cp sample\include\my_adlib.txt                                      \users\jum002\Documents\GitHub\ADT\sample\common
cp sample\include\my_extlib.txt                                     \users\jum002\Documents\GitHub\ADT\sample\common
cp sample\include\pascal_macros.txt                                 \users\jum002\Documents\GitHub\ADT\sample\common
cp sample\include\stdlib.f                                          \users\jum002\Documents\GitHub\ADT\sample\common
cp sample\Mseom\D_Mseom.cpp                                         \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\D_Mseom.hpp                                         \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\D_MseomMin.cpp                                      \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\D_MseomMin.hpp                                      \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\install_debug_lib.bat                               \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\install_lib.bat                                     \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom.bbdef                                         \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom.cpp                                           \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom.hpp                                           \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom.mk                                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom.vcxproj                                       \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom_reg_1.hpp                                     \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom_reg_2.hpp                                     \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Mseom_registration.cpp                              \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\MseomMin.cpp                                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\MseomMin.hpp                                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_array_plans.hpp                                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_array_plans_copy.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_array_plans_init.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_constructor_args.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_constructor_arrays_phase_1.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_constructor_call_args.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_constructor_locals.hpp                           \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_constructor_scalars_phase_1.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_decl_lib_interface_constructor.hpp               \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_decl_lib_interface_globals.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_decl_lib_interface_methods.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_impl_lib_interface_constructor.hpp               \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_impl_lib_interface_globals.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_impl_lib_interface_methods.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_impl_lib_registration.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\Om_R_interface.r                                    \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_array_plans.hpp                                 \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_array_plans_copy.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_array_plans_init.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_constructor_args.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_constructor_arrays_phase_1.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_constructor_arrays_phase_2.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_constructor_call_args.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_constructor_locals.hpp                          \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_constructor_scalars_phase_1.hpp                 \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_constructor_scalars_phase_2.hpp                 \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_decl_lib_interface_constructor.hpp              \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_decl_lib_interface_globals.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_decl_lib_interface_methods.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_impl_lib_interface_constructor.hpp              \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_impl_lib_interface_globals.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_impl_lib_interface_methods.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_impl_lib_registration.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\OmB_R_interface.r                                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Mseom\run_mk                                              \users\jum002\Documents\GitHub\ADT\sample\Mseom
cp sample\Rosenbrock\build_lib.bat                                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\build_lib.sh                                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\d_Rosenbrock.cpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\d_Rosenbrock.hpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\dR_Rosenbrock.cpp                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\dR_Rosenbrock.hpp                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\MinRosenbrock_Unit.pas                         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\R_Rosenbrock.cpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\R_Rosenbrock.hpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_array_plans.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_array_plans_copy.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_array_plans_init.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_constructor_args.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_constructor_arrays_phase_1.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_constructor_call_args.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_constructor_locals.hpp                      \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_constructor_scalars_phase_1.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_decl_lib_interface_constructor.hpp          \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_decl_lib_interface_globals.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_decl_lib_interface_methods.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_impl_lib_interface_constructor.hpp          \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_impl_lib_interface_globals.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_impl_lib_interface_methods.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_impl_lib_registration.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rb_R_interface.r                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock.cpp                                 \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock.hpp                                 \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock.lpi                                 \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock.mk                                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock.R                                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock.vcxproj                             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock_reg_1.hpp                           \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\Rosenbrock_reg_2.hpp                           \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RosenbrockPas.lpr                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RosenbrockPas.mk                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RosenbrockPas.R                                \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\run_mk                                         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_array_plans.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_array_plans_copy.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_array_plans_init.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_constructor_args.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_constructor_arrays_phase_1.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_constructor_call_args.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_constructor_locals.hpp                     \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_constructor_scalars_phase_1.hpp            \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_decl_lib_interface_constructor.hpp         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_decl_lib_interface_globals.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_decl_lib_interface_methods.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_impl_lib_interface_constructor.hpp         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_impl_lib_interface_globals.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_impl_lib_interface_methods.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_impl_lib_registration.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp sample\Rosenbrock\RRb_R_interface.r                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
cp src\adtautomate.cpp                                              \users\jum002\Documents\GitHub\ADT\src
cp src\adtautomate.hpp                                              \users\jum002\Documents\GitHub\ADT\src
cp src\adtblackbox.cpp                                              \users\jum002\Documents\GitHub\ADT\src
cp src\adtblackbox.cpp                                              \users\jum002\Documents\GitHub\ADT\src
cp src\adtcommon.cpp                                                \users\jum002\Documents\GitHub\ADT\src
cp src\adtcommon.hpp                                                \users\jum002\Documents\GitHub\ADT\src
cp src\adtcpp.cpp                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\adtcpp.hpp                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\adtdelphi.cpp                                                \users\jum002\Documents\GitHub\ADT\src
cp src\adtdelphi.hpp                                                \users\jum002\Documents\GitHub\ADT\src
cp src\adtexpression.cpp                                            \users\jum002\Documents\GitHub\ADT\src
cp src\adtexpression.hpp                                            \users\jum002\Documents\GitHub\ADT\src
cp src\adtfortran.cpp                                               \users\jum002\Documents\GitHub\ADT\src
cp src\adtfortran.hpp                                               \users\jum002\Documents\GitHub\ADT\src
cp src\adtjava.cpp                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\adtjava.hpp                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\adtmake.cpp                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\adtmake.hpp                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\adtparser.cpp                                                \users\jum002\Documents\GitHub\ADT\src
cp src\adtparser.hpp                                                \users\jum002\Documents\GitHub\ADT\src
cp src\adtutils.cpp                                                 \users\jum002\Documents\GitHub\ADT\src
cp src\adtutils.hpp                                                 \users\jum002\Documents\GitHub\ADT\src
cp src\adtver.hpp                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_inc.h                                              \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_l.c                                                \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_l.l                                                \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_l_wrap.c                                           \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_y.c                                                \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_y.h                                                \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_y.y                                                \users\jum002\Documents\GitHub\ADT\src
cp src\black_box_y_wrap.c                                           \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_inc.h                                                    \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_l.c                                                      \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_l.l                                                      \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_l_wrap.c                                                 \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_y.c                                                      \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_y.h                                                      \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_y.y                                                      \users\jum002\Documents\GitHub\ADT\src
cp src\cpp_y_wrap.c                                                 \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_inc.h                                                 \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_l.c                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_l.l                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_l_wrap.c                                              \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_y.c                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_y.h                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_y.y                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\delphi_y_wrap.c                                              \users\jum002\Documents\GitHub\ADT\src
cp src\expression_inc.h                                             \users\jum002\Documents\GitHub\ADT\src
cp src\expression_l.c                                               \users\jum002\Documents\GitHub\ADT\src
cp src\expression_l.l                                               \users\jum002\Documents\GitHub\ADT\src
cp src\expression_l_wrap.c                                          \users\jum002\Documents\GitHub\ADT\src
cp src\expression_y.c                                               \users\jum002\Documents\GitHub\ADT\src
cp src\expression_y.h                                               \users\jum002\Documents\GitHub\ADT\src
cp src\expression_y.y                                               \users\jum002\Documents\GitHub\ADT\src
cp src\expression_y_wrap.c                                          \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_inc.h                                                \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_l.c                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_l.l                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_l_wrap.c                                             \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_y.c                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_y.h                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_y.y                                                  \users\jum002\Documents\GitHub\ADT\src
cp src\fortran_y_wrap.c                                             \users\jum002\Documents\GitHub\ADT\src
cp src\java_inc.h                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\java_l.c                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\java_l.l                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\java_l_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
cp src\java_y.c                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\java_y.h                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\java_y.y                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\java_y_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
cp src\make_inc.h                                                   \users\jum002\Documents\GitHub\ADT\src
cp src\make_l.c                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\make_l.l                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\make_l_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
cp src\make_y.c                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\make_y.h                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\make_y.y                                                     \users\jum002\Documents\GitHub\ADT\src
cp src\make_y_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
cp src\pragmas.h                                                    \users\jum002\Documents\GitHub\ADT\src
cp src\tap.pl                                                       \users\jum002\Documents\GitHub\ADT\src
cp src\ADLib\ts_optim.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\ts_lbfgsb.cpp                                          \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\readme.txt                                             \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtthreads.cpp                                         \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtthreads.hpp                                         \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtstack.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtstack.hpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtR.cpp                                               \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtR.hpp                                               \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtparallel.cpp                                        \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtparallel.hpp                                        \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtmaths.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtmaths.hpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtlibtests.cpp                                        \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adterror.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtdiff.cpp                                            \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtdiff.hpp                                            \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtarrays.cpp                                          \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLib\adtarrays.hpp                                          \users\jum002\Documents\GitHub\ADT\src\ADLib
cp src\ADLibPascal\*.inc                                            \users\jum002\Documents\GitHub\ADT\src\ADLibPascal
cp src\ADLibPascal\*.pas                                            \users\jum002\Documents\GitHub\ADT\src\ADLibPascal
cp src\ADLibPascal\make_template_code                               \users\jum002\Documents\GitHub\ADT\src\ADLibPascal
cp src\ADLibPascal\fcl-stl\*.pp                                     \users\jum002\Documents\GitHub\ADT\src\ADLibPascal\fcl-stl
cp src\fdlibm-5.2\*                                                 \users\jum002\Documents\GitHub\ADT\src\fdlibm-5.2
cp src\fdlibm-5.2\src\*                                             \users\jum002\Documents\GitHub\ADT\src\fdlibm-5.2\src
cp src\RMath\include\*.h                                            \users\jum002\Documents\GitHub\ADT\src\RMath\include
cp src\RMath\include\R_ext\*.h                                      \users\jum002\Documents\GitHub\ADT\src\RMath\include\R_ext
cp src\RMath\lib\*                                                  \users\jum002\Documents\GitHub\ADT\src\RMath\lib
cp src\RMath\lib\x32\*                                              \users\jum002\Documents\GitHub\ADT\src\RMath\lib\x32
cp templates\make\autoconf\*                                        \users\jum002\Documents\GitHub\ADT\templates\make\autoconf
cp templates\make\VisualStudio\*                                    \users\jum002\Documents\GitHub\ADT\templates\make\VisualStudio
cp templates\R\newadt\man\*                                         \users\jum002\Documents\GitHub\ADT\templates\R\newadt\man
cp templates\R\newadt\R\*                                           \users\jum002\Documents\GitHub\ADT\templates\R\newadt\R
cp templates\R\newadt\*                                             \users\jum002\Documents\GitHub\ADT\templates\R\newadt
cp templates\source\cpp\*                                           \users\jum002\Documents\GitHub\ADT\templates\source\cpp
cp templates\source\pascal\*                                        \users\jum002\Documents\GitHub\ADT\templates\source\pascal
