copy /Y ChangeLog                                                        \users\jum002\Documents\GitHub\ADT
copy /Y config.h                                                         \users\jum002\Documents\GitHub\ADT
copy /Y configure.ac                                                     \users\jum002\Documents\GitHub\ADT
copy /Y COPYING                                                          \users\jum002\Documents\GitHub\ADT
copy /Y exclude.txt                                                      \users\jum002\Documents\GitHub\ADT
copy /Y gitsync.bat                                                      \users\jum002\Documents\GitHub\ADT
copy /Y init_config.sh                                                   \users\jum002\Documents\GitHub\ADT
copy /Y INSTALL                                                          \users\jum002\Documents\GitHub\ADT
copy /Y Makefile.am                                                      \users\jum002\Documents\GitHub\ADT
copy /Y README                                                           \users\jum002\Documents\GitHub\ADT
copy /Y WinInstall32.iss                                                 \users\jum002\Documents\GitHub\ADT
copy /Y WinInstall64.iss                                                 \users\jum002\Documents\GitHub\ADT
copy /Y ylwrap                                                           \users\jum002\Documents\GitHub\ADT
copy /Y doc\ADT.layout                                                   \users\jum002\Documents\GitHub\ADT\doc
copy /Y doc\Presentation                                                 \users\jum002\Documents\GitHub\ADT\doc
copy /Y doc\users-manual.lyx                                             \users\jum002\Documents\GitHub\ADT\doc
copy /Y doc\users-manual.pdf                                             \users\jum002\Documents\GitHub\ADT\doc
copy /Y doc\Presentation\ADT-flowchart.png                               \users\jum002\Documents\GitHub\ADT\doc\Presentation
copy /Y doc\Presentation\presentation.html                               \users\jum002\Documents\GitHub\ADT\doc\Presentation
copy /Y objs\ADLib.vcxproj                                               \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\ADLibErr.vcxproj                                            \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\ADLibR.vcxproj                                              \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\ADLibTest.vcxproj                                           \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\fdlibm-5.2.vcxproj                                          \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\adt.sdf                                                     \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\adt.sln                                                     \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\Makefile.am                                                 \users\jum002\Documents\GitHub\ADT\objs
copy /Y objs\ADLib\Makefile.am                                           \users\jum002\Documents\GitHub\ADT\objs\ADLib
copy /Y objs\ADLibPascal\Windows\Win32\build_lib.bat                     \users\jum002\Documents\GitHub\ADT\objs\ADLibPascal\Windows\Win32
copy /Y objs\ADLibPascal\Windows\x64\build_lib.bat                       \users\jum002\Documents\GitHub\ADT\objs\ADLibPascal\Windows\x64
copy /Y objs\ADLibTest\Makefile.am                                       \users\jum002\Documents\GitHub\ADT\objs\ADLibTest
copy /Y objs\blackbox_parse\Makefile.am                                  \users\jum002\Documents\GitHub\ADT\objs\blackbox_parse
copy /Y objs\cpp_parse\Makefile.am                                       \users\jum002\Documents\GitHub\ADT\objs\cpp_parse
copy /Y objs\delphi_parse\Makefile.am                                    \users\jum002\Documents\GitHub\ADT\objs\delphi_parse
copy /Y objs\expression_parse\Makefile.am                                \users\jum002\Documents\GitHub\ADT\objs\expression_parse
copy /Y objs\fortran_parse\Makefile.am                                   \users\jum002\Documents\GitHub\ADT\objs\fortran_parse
copy /Y objs\java_parse\Makefile.am                                      \users\jum002\Documents\GitHub\ADT\objs\java_parse
copy /Y objs\make_parse\Makefile.am                                      \users\jum002\Documents\GitHub\ADT\objs\make_parse
copy /Y objs\sample\ArrayTest\Makefile.am                                \users\jum002\Documents\GitHub\ADT\objs\sample\ArrayTest
copy /Y objs\sample\Mseom\Makefile.am                                    \users\jum002\Documents\GitHub\ADT\objs\sample\Mseom
copy /Y objs\sample\Rosenbrock\Makefile.am                               \users\jum002\Documents\GitHub\ADT\objs\sample\Rosenbrock
copy /Y sample\ArrayTest\build_lib.bat                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest.bbdef                                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest.cpp                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest.hpp                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest.lpi                                   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest.mk                                    \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest.R                                     \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest.vcxproj                               \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest_registration.cpp                      \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTest_Unit.pas                              \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTestPas.lpr                                \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTestPas.mk                                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\ArrayTestPas.R                                  \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\AT_R_interface.r                                \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\build_lib.sh                                    \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\run_mk                                          \users\jum002\Documents\GitHub\ADT\sample\ArrayTest
copy /Y sample\ArrayTest\include\AT_array_plans.hpp                      \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_array_plans_copy.hpp                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_array_plans_init.hpp                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_constructor_args.hpp                 \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_constructor_arrays_phase_1.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_constructor_call_args.hpp            \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_constructor_locals.hpp               \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_constructor_scalars_phase_1.hpp      \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_decl_lib_interface_constructor.hpp   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_decl_lib_interface_globals.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_decl_lib_interface_methods.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_impl_lib_interface_constructor.hpp   \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_impl_lib_interface_globals.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_impl_lib_interface_methods.hpp       \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\ArrayTest\include\AT_impl_lib_registration.hpp            \users\jum002\Documents\GitHub\ADT\sample\ArrayTest\include
copy /Y sample\include\common.bbdef                                      \users\jum002\Documents\GitHub\ADT\sample\include
copy /Y sample\include\cpp_macros.txt                                    \users\jum002\Documents\GitHub\ADT\sample\include
copy /Y sample\include\my_adlib.txt                                      \users\jum002\Documents\GitHub\ADT\sample\include
copy /Y sample\include\my_extlib.txt                                     \users\jum002\Documents\GitHub\ADT\sample\include
copy /Y sample\include\pascal_macros.txt                                 \users\jum002\Documents\GitHub\ADT\sample\include
copy /Y sample\include\stdlib.f                                          \users\jum002\Documents\GitHub\ADT\sample\include
copy /Y sample\Mseom\D_Mseom.cpp                                         \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\D_Mseom.hpp                                         \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\D_MseomMin.cpp                                      \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\D_MseomMin.hpp                                      \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\install_debug_lib.bat                               \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\install_lib.bat                                     \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom.bbdef                                         \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom.cpp                                           \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom.hpp                                           \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom.mk                                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom.vcxproj                                       \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom_reg_1.hpp                                     \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom_reg_2.hpp                                     \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Mseom_registration.cpp                              \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\MseomMin.cpp                                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\MseomMin.hpp                                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_array_plans.hpp                                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_array_plans_copy.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_array_plans_init.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_constructor_args.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_constructor_arrays_phase_1.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_constructor_call_args.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_constructor_locals.hpp                           \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_constructor_scalars_phase_1.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_decl_lib_interface_constructor.hpp               \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_decl_lib_interface_globals.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_decl_lib_interface_methods.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_impl_lib_interface_constructor.hpp               \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_impl_lib_interface_globals.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_impl_lib_interface_methods.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_impl_lib_registration.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\Om_R_interface.r                                    \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_array_plans.hpp                                 \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_array_plans_copy.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_array_plans_init.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_constructor_args.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_constructor_arrays_phase_1.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_constructor_arrays_phase_2.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_constructor_call_args.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_constructor_locals.hpp                          \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_constructor_scalars_phase_1.hpp                 \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_constructor_scalars_phase_2.hpp                 \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_decl_lib_interface_constructor.hpp              \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_decl_lib_interface_globals.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_decl_lib_interface_methods.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_impl_lib_interface_constructor.hpp              \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_impl_lib_interface_globals.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_impl_lib_interface_methods.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_impl_lib_registration.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\OmB_R_interface.r                                   \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Mseom\run_mk                                              \users\jum002\Documents\GitHub\ADT\sample\Mseom
copy /Y sample\Rosenbrock\build_lib.bat                                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\build_lib.sh                                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\d_Rosenbrock.cpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\d_Rosenbrock.hpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\dR_Rosenbrock.cpp                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\dR_Rosenbrock.hpp                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\MinRosenbrock_Unit.pas                         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\R_Rosenbrock.cpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\R_Rosenbrock.hpp                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_array_plans.hpp                             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_array_plans_copy.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_array_plans_init.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_constructor_args.hpp                        \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_constructor_arrays_phase_1.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_constructor_call_args.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_constructor_locals.hpp                      \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_constructor_scalars_phase_1.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_decl_lib_interface_constructor.hpp          \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_decl_lib_interface_globals.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_decl_lib_interface_methods.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_impl_lib_interface_constructor.hpp          \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_impl_lib_interface_globals.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_impl_lib_interface_methods.hpp              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_impl_lib_registration.hpp                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rb_R_interface.r                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock.cpp                                 \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock.hpp                                 \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock.lpi                                 \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock.mk                                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock.R                                   \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock.vcxproj                             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock_reg_1.hpp                           \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\Rosenbrock_reg_2.hpp                           \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RosenbrockPas.lpr                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RosenbrockPas.mk                               \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RosenbrockPas.R                                \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\run_mk                                         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_array_plans.hpp                            \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_array_plans_copy.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_array_plans_init.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_constructor_args.hpp                       \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_constructor_arrays_phase_1.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_constructor_call_args.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_constructor_locals.hpp                     \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_constructor_scalars_phase_1.hpp            \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_decl_lib_interface_constructor.hpp         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_decl_lib_interface_globals.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_decl_lib_interface_methods.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_impl_lib_interface_constructor.hpp         \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_impl_lib_interface_globals.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_impl_lib_interface_methods.hpp             \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_impl_lib_registration.hpp                  \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y sample\Rosenbrock\RRb_R_interface.r                              \users\jum002\Documents\GitHub\ADT\sample\Rosenbrock
copy /Y src\adtautomate.cpp                                              \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtautomate.hpp                                              \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtblackbox.cpp                                              \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtblackbox.hpp                                              \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtcommon.cpp                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtcommon.hpp                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtcpp.cpp                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtcpp.hpp                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtdelphi.cpp                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtdelphi.hpp                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtexpression.cpp                                            \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtexpression.hpp                                            \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtfortran.cpp                                               \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtfortran.hpp                                               \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtjava.cpp                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtjava.hpp                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtmake.cpp                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtmake.hpp                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtparser.cpp                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtparser.hpp                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtutils.cpp                                                 \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtutils.hpp                                                 \users\jum002\Documents\GitHub\ADT\src
copy /Y src\adtver.hpp                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_inc.h                                              \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_l.c                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_l.l                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_l_wrap.c                                           \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_y.c                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_y.h                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_y.y                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\black_box_y_wrap.c                                           \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_inc.h                                                    \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_l.c                                                      \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_l.l                                                      \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_l_wrap.c                                                 \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_y.c                                                      \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_y.h                                                      \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_y.y                                                      \users\jum002\Documents\GitHub\ADT\src
copy /Y src\cpp_y_wrap.c                                                 \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_inc.h                                                 \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_l.c                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_l.l                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_l_wrap.c                                              \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_y.c                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_y.h                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_y.y                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\delphi_y_wrap.c                                              \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_inc.h                                             \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_l.c                                               \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_l.l                                               \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_l_wrap.c                                          \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_y.c                                               \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_y.h                                               \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_y.y                                               \users\jum002\Documents\GitHub\ADT\src
copy /Y src\expression_y_wrap.c                                          \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_inc.h                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_l.c                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_l.l                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_l_wrap.c                                             \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_y.c                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_y.h                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_y.y                                                  \users\jum002\Documents\GitHub\ADT\src
copy /Y src\fortran_y_wrap.c                                             \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_inc.h                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_l.c                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_l.l                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_l_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_y.c                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_y.h                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_y.y                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\java_y_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\lexer.h                                                      \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_inc.h                                                   \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_l.c                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_l.l                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_l_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_y.c                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_y.h                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_y.y                                                     \users\jum002\Documents\GitHub\ADT\src
copy /Y src\make_y_wrap.c                                                \users\jum002\Documents\GitHub\ADT\src
copy /Y src\pragmas.h                                                    \users\jum002\Documents\GitHub\ADT\src
copy /Y src\tap.pl                                                       \users\jum002\Documents\GitHub\ADT\src
copy /Y src\ADLib\ts_optim.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\ts_lbfgsb.cpp                                          \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\readme.txt                                             \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtthreads.cpp                                         \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtthreads.hpp                                         \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtstack.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtstack.hpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtR.cpp                                               \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtR.hpp                                               \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtparallel.cpp                                        \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtparallel.hpp                                        \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtmaths.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtmaths.hpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtlibtests.cpp                                        \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adterror.cpp                                           \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtdiff.cpp                                            \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtdiff.hpp                                            \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtarrays.cpp                                          \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLib\adtarrays.hpp                                          \users\jum002\Documents\GitHub\ADT\src\ADLib
copy /Y src\ADLibPascal\*.inc                                            \users\jum002\Documents\GitHub\ADT\src\ADLibPascal
copy /Y src\ADLibPascal\*.pas                                            \users\jum002\Documents\GitHub\ADT\src\ADLibPascal
copy /Y src\ADLibPascal\make_template_code                               \users\jum002\Documents\GitHub\ADT\src\ADLibPascal
copy /Y src\ADLibPascal\fcl-stl\*.pp                                     \users\jum002\Documents\GitHub\ADT\src\ADLibPascal\fcl-stl
copy /Y src\fdlibm-5.2\*                                                 \users\jum002\Documents\GitHub\ADT\src\fdlibm-5.2
copy /Y src\fdlibm-5.2\src\*                                             \users\jum002\Documents\GitHub\ADT\src\fdlibm-5.2\src
copy /Y src\RMath\include\*.h                                            \users\jum002\Documents\GitHub\ADT\src\RMath\include
copy /Y src\RMath\include\R_ext\*.h                                      \users\jum002\Documents\GitHub\ADT\src\RMath\include\R_ext
copy /Y src\RMath\lib\*                                                  \users\jum002\Documents\GitHub\ADT\src\RMath\lib
copy /Y src\RMath\lib\x32\*                                              \users\jum002\Documents\GitHub\ADT\src\RMath\lib\x32
copy /Y templates\make\autoconf\*                                        \users\jum002\Documents\GitHub\ADT\templates\make\autoconf
copy /Y templates\make\VisualStudio\*                                    \users\jum002\Documents\GitHub\ADT\templates\make\VisualStudio
copy /Y templates\make\Lazarus\*                                         \users\jum002\Documents\GitHub\ADT\templates\make\Lazarus
copy /Y templates\make\Xcode\*                                           \users\jum002\Documents\GitHub\ADT\templates\make\Xcode
copy /Y templates\R\newadt\man\*                                         \users\jum002\Documents\GitHub\ADT\templates\R\newadt\man
copy /Y templates\R\newadt\R\*                                           \users\jum002\Documents\GitHub\ADT\templates\R\newadt\R
copy /Y templates\R\newadt\*                                             \users\jum002\Documents\GitHub\ADT\templates\R\newadt
copy /Y templates\R\createDistro.bat                                     \users\jum002\Documents\GitHub\ADT\templates\R
copy /Y templates\source\cpp\*                                           \users\jum002\Documents\GitHub\ADT\templates\source\cpp
copy /Y templates\source\pascal\*                                        \users\jum002\Documents\GitHub\ADT\templates\source\pascal
