1 File: cygwin warning:
2 File:   MS-DOS style path detected: .\work\dR_REDev.1.f95
3 File:   Preferred POSIX equivalent is: ./work/dR_REDev.1.f95
4 File:   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
5 File:   Consult the user's guide for more details about POSIX paths:
6 File:     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
7 r_redev__laplace: (DF03) variable m_pi is used before initialized
8 r_redev__hessianre: (TC24) Wrong number of dimensions for array phessian: 2 expected, and 1 given
9 r_redev__dlognorm: (DF03) variable m_pi is used before initialized
10 r_redev__thetaloglikelihood_bre: (TC19) Equality test on reals is not reliable
11 r_redev__thetaloglikelihood_bre: (TC19) Equality test on reals is not reliable
12 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
13 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
14 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
15 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
16 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
17 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
18 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
19 r_redev__thetaloglikelihood_bre_dre: (TC19) Equality test on reals is not reliable
20 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function pushreal8 for arguments Arg1=(in) /adstack_r8/[0,inf[=(in;out)
21 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function pushreal8 for arguments Arg1=(in) /adstack_r8/[0,inf[=(in;out)
22 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function pushreal8 for arguments Arg1=(in) /adstack_r8/[0,inf[=(in;out)
23 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function pushreal8 for arguments Arg1=(in) /adstack_r8/[0,inf[=(in;out)
24 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function pushreal8 for arguments Arg1=(in) /adstack_r8/[0,inf[=(in;out)
25 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function pushreal8 for arguments Arg1=(in) /adstack_r8/[0,inf[=(in;out)
26 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function popreal8 for arguments Arg1=(in;out) /adstack_r8/[0,inf[=(in;out)
27 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function popreal8 for arguments Arg1=(in;out) /adstack_r8/[0,inf[=(in;out)
28 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function popreal8 for arguments Arg1=(in;out) /adstack_r8/[0,inf[=(in;out)
29 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function popreal8 for arguments Arg1=(in;out) /adstack_r8/[0,inf[=(in;out)
30 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function popreal8 for arguments Arg1=(in;out) /adstack_r8/[0,inf[=(in;out)
31 r_redev__thetaloglikelihood_bre_dre: (AD09) Please provide a differential of function popreal8 for arguments Arg1=(in;out) /adstack_r8/[0,inf[=(in;out)
32 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
33 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
34 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
35 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
36 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
37 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
38 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
39 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
40 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
41 r_redev__thetaloglikelihood_bre_dpar: (TC19) Equality test on reals is not reliable
42 r_redev__thetaloglikelihood_bpar: (TC19) Equality test on reals is not reliable
43 r_redev__thetaloglikelihood_bpar: (TC19) Equality test on reals is not reliable
44 r_redev__thetaloglikelihood_bpar: (TC19) Equality test on reals is not reliable
45 r_redev__thetaloglikelihood_bpar: (TC19) Equality test on reals is not reliable
