  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1B; const pRefArray : ARRAY_1B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2B; const pRefArray : ARRAY_2B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3B; const pRefArray : ARRAY_3B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4B; const pRefArray : ARRAY_4B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5B; const pRefArray : ARRAY_5B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6B; const pRefArray : ARRAY_6B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7B; const pRefArray : ARRAY_7B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8B; const pRefArray : ARRAY_8B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9B; const pRefArray : ARRAY_9B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10B; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10B; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10B; const pRefArray : ARRAY_10B) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10B) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1C; const pRefArray : ARRAY_1C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2C; const pRefArray : ARRAY_2C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3C; const pRefArray : ARRAY_3C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4C; const pRefArray : ARRAY_4C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5C; const pRefArray : ARRAY_5C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6C; const pRefArray : ARRAY_6C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7C; const pRefArray : ARRAY_7C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8C; const pRefArray : ARRAY_8C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9C; const pRefArray : ARRAY_9C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10C; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10C; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10C; const pRefArray : ARRAY_10C) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10C) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UC; const pRefArray : ARRAY_1UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UC; const pRefArray : ARRAY_2UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UC; const pRefArray : ARRAY_3UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UC; const pRefArray : ARRAY_4UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UC; const pRefArray : ARRAY_5UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UC; const pRefArray : ARRAY_6UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UC; const pRefArray : ARRAY_7UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UC; const pRefArray : ARRAY_8UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UC; const pRefArray : ARRAY_9UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10UC; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UC; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UC; const pRefArray : ARRAY_10UC) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UC) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1I; const pRefArray : ARRAY_1I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2I; const pRefArray : ARRAY_2I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3I; const pRefArray : ARRAY_3I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4I; const pRefArray : ARRAY_4I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5I; const pRefArray : ARRAY_5I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6I; const pRefArray : ARRAY_6I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7I; const pRefArray : ARRAY_7I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8I; const pRefArray : ARRAY_8I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9I; const pRefArray : ARRAY_9I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10I; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10I; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10I; const pRefArray : ARRAY_10I) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10I) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1S; const pRefArray : ARRAY_1S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2S; const pRefArray : ARRAY_2S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3S; const pRefArray : ARRAY_3S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4S; const pRefArray : ARRAY_4S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5S; const pRefArray : ARRAY_5S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6S; const pRefArray : ARRAY_6S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7S; const pRefArray : ARRAY_7S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8S; const pRefArray : ARRAY_8S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9S; const pRefArray : ARRAY_9S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10S; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10S; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10S; const pRefArray : ARRAY_10S) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10S) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1US; const pRefArray : ARRAY_1US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2US; const pRefArray : ARRAY_2US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3US; const pRefArray : ARRAY_3US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4US; const pRefArray : ARRAY_4US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5US; const pRefArray : ARRAY_5US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6US; const pRefArray : ARRAY_6US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7US; const pRefArray : ARRAY_7US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8US; const pRefArray : ARRAY_8US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9US; const pRefArray : ARRAY_9US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10US; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10US; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10US; const pRefArray : ARRAY_10US) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10US) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1L; const pRefArray : ARRAY_1L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2L; const pRefArray : ARRAY_2L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3L; const pRefArray : ARRAY_3L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4L; const pRefArray : ARRAY_4L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5L; const pRefArray : ARRAY_5L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6L; const pRefArray : ARRAY_6L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7L; const pRefArray : ARRAY_7L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8L; const pRefArray : ARRAY_8L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9L; const pRefArray : ARRAY_9L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10L; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10L; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10L; const pRefArray : ARRAY_10L) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10L) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UL; const pRefArray : ARRAY_1UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UL; const pRefArray : ARRAY_2UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UL; const pRefArray : ARRAY_3UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UL; const pRefArray : ARRAY_4UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UL; const pRefArray : ARRAY_5UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UL; const pRefArray : ARRAY_6UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UL; const pRefArray : ARRAY_7UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UL; const pRefArray : ARRAY_8UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UL; const pRefArray : ARRAY_9UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10UL; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UL; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UL; const pRefArray : ARRAY_10UL) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UL) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1F; const pRefArray : ARRAY_1F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2F; const pRefArray : ARRAY_2F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3F; const pRefArray : ARRAY_3F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4F; const pRefArray : ARRAY_4F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5F; const pRefArray : ARRAY_5F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6F; const pRefArray : ARRAY_6F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7F; const pRefArray : ARRAY_7F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8F; const pRefArray : ARRAY_8F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9F; const pRefArray : ARRAY_9F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10F; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10F; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10F; const pRefArray : ARRAY_10F) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10F) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_1D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1D; const pRefArray : ARRAY_1D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_1D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_2D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2D; const pRefArray : ARRAY_2D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_2D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_3D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3D; const pRefArray : ARRAY_3D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_3D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_4D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4D; const pRefArray : ARRAY_4D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_4D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_5D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5D; const pRefArray : ARRAY_5D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_5D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_6D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6D; const pRefArray : ARRAY_6D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_6D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_7D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7D; const pRefArray : ARRAY_7D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_7D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_8D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8D; const pRefArray : ARRAY_8D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_8D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_9D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9D; const pRefArray : ARRAY_9D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_9D) ; static ; overload;
  //  ----------------------------------------------------------------------------
  // existing array query method - use to obtain an array from a pointer
  // passed from R that has previously been mapped by this array plan
  function existing(var pArray : ARRAY_10D; pExisting : pchar) : boolean ; overload;

  // New array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10D; pExisting : pchar = nil) : boolean ; overload;

  // Same shape array creation method
  function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10D; const pRefArray : ARRAY_10D) : boolean ; static ; overload;

  // array destruction method
  procedure destroy(rAllocator : AdtMemAllocator; var pArray : ARRAY_10D) ; static ; overload;
