// Simplified array creation methods
// 1D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_1<T>;
                             nBaseIndex, nSize : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 2D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_2<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 3D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_3<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 4D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_4<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             nBaseIndex4, nSize4 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 5D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_5<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             nBaseIndex4, nSize4 : longint;
                             nBaseIndex5, nSize5 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 6D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_6<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             nBaseIndex4, nSize4 : longint;
                             nBaseIndex5, nSize5 : longint;
                             nBaseIndex6, nSize6 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 7D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_7<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             nBaseIndex4, nSize4 : longint;
                             nBaseIndex5, nSize5 : longint;
                             nBaseIndex6, nSize6 : longint;
                             nBaseIndex7, nSize7 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 8D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_8<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             nBaseIndex4, nSize4 : longint;
                             nBaseIndex5, nSize5 : longint;
                             nBaseIndex6, nSize6 : longint;
                             nBaseIndex7, nSize7 : longint;
                             nBaseIndex8, nSize8 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 9D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_9<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             nBaseIndex4, nSize4 : longint;
                             nBaseIndex5, nSize5 : longint;
                             nBaseIndex6, nSize6 : longint;
                             nBaseIndex7, nSize7 : longint;
                             nBaseIndex8, nSize8 : longint;
                             nBaseIndex9, nSize9 : longint;
                             pExisting : pchar = nil) : boolean ; overload;

// 10D
function AdtArrayPlan_create(var rAllocator : AdtMemAllocator;
                             var pArray : ARRAY_10<T>;
                             nBaseIndex1, nSize1 : longint;
                             nBaseIndex2, nSize2 : longint;
                             nBaseIndex3, nSize3 : longint;
                             nBaseIndex4, nSize4 : longint;
                             nBaseIndex5, nSize5 : longint;
                             nBaseIndex6, nSize6 : longint;
                             nBaseIndex7, nSize7 : longint;
                             nBaseIndex8, nSize8 : longint;
                             nBaseIndex9, nSize9 : longint;
                             nBaseIndex10, nSize10 : longint;
                             pExisting : pchar = nil) : boolean ; overload;
