//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10B; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10B; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10C; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10C; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10UC; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UC; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10I; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10I; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10S; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10S; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10US; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10US; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10L; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10L; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10UL; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10UL; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10F; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10F; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_1D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_1D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_2D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_2D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_3D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_3D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_4D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_4D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_5D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_5D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_6D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_6D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_7D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_7D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_8D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_8D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_9D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_9D; pExisting : pchar = nil) : boolean ; overload;
//  ----------------------------------------------------------------------------
// existing array query method - use to obtain an array from a pointer
// passed from R that has previously been mapped by this array plan
function existing(var pArray : ARRAY_10D; pExisting : pchar) : boolean ; overload;

// New array creation method
function create(rAllocator : AdtMemAllocator; var pArray : ARRAY_10D; pExisting : pchar = nil) : boolean ; overload;
