#line 1 "..\\src\\black_box_l.c"

#line 3 "..\\src\\black_box_l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[221] =
    {   0,
        0,    0,    0,    0,   56,   54,   53,   54,   54,    1,
        2,    3,    4,   52,   50,   51,   52,   37,   38,   41,
       39,   36,   40,   45,   44,   48,   34,   35,    1,    2,
       46,   46,   46,   46,   46,   43,   46,   46,   46,   46,
       46,   46,   46,   46,   46,    3,    4,    6,    5,    7,
        0,    8,   42,   49,   49,   48,    0,   46,    0,   46,
        0,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       33,   12,   46,   46,   46,    0,   49,   49,   47,    0,
       46,   32,   46,   46,   46,   46,   46,   46,   46,   15,
       46,   46,   13,   46,   46,   46,    0,   49,   47,   47,

       46,   46,   46,   46,   46,   46,   46,   31,   46,   46,
       46,   16,   46,   47,   46,   46,   46,   46,   14,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   11,   46,
       46,   46,   46,   20,   46,   18,   46,   17,   46,   46,
       26,   46,   46,   46,   46,   46,   46,   46,    9,   46,
       46,   46,   46,   46,   46,   46,   46,   19,   46,   46,
       10,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       21,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   25,   46,   23,   22,   46,   46,   27,   46,   46,
       46,   46,   30,   24,   46,   46,   29,   46,   28,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
        1,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   24,   24,   24,   25,   26,   24,   27,   28,   24,
       24,   29,   24,   30,   24,   24,   31,   32,   24,   24,
        1,    1,    1,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   24,   24,   44,   45,   46,
       47,   48,   24,   49,   50,   51,   52,   24,   24,   53,
       54,   24,   55,    1,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    3,    4,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1
    } ;

static const flex_int16_t yy_base[228] =
    {   0,
        0,    2,   58,    0,  160,  713,  713,  147,    1,  713,
      713,  713,  713,  713,  713,  713,  151,  713,  713,    3,
      713,  713,  713,  136,   13,   10,  713,  713,  713,  713,
       13,   15,   19,  104,  105,  713,  106,  110,  111,  112,
      116,  117,  118,  122,  123,  713,  713,  713,  713,  713,
      145,  713,  713,  143,  151,   21,    0,   24,  133,   25,
      120,  124,  132,  165,  167,  174,  175,  182,  183,  187,
       26,  188,  189,  194,  193,   34,  713,  209,  129,    0,
       34,  713,  205,  199,  201,  128,  212,  231,  213,   35,
      236,  241,   39,  240,  245,  246,   39,  252,   40,   14,

      256,  255,  257,  271,  272,  277,  279,  286,  288,  290,
      294,  292,  296,    8,  302,  308,  304,  313,  314,  318,
      323,  324,  330,  331,  336,  343,  335,  347,  345,  351,
      353,  355,  357,  365,  366,  370,  371,  376,  377,  382,
      401,  386,  384,  392,  393,  410,  422,  423,  424,  428,
      429,  434,  436,  435,  440,  441,  442,  447,  448,  452,
      453,  458,  469,  474,  475,  483,  484,  485,  489,  490,
      491,  495,  496,  497,  501,  503,  510,  512,  511,  517,
      523,  530,  531,  537,  539,  543,  544,  550,  554,  556,
      558,  562,  560,  566,  570,  572,  580,  581,  586,  591,

      592,  598,  603,  599,  604,  610,  611,  616,  622,  628,
      630,  629,  634,  635,  639,  640,  641,  645,  646,  713,
      691,  696,  700,    6,  704,    1,  707
    } ;

static const flex_int16_t yy_def[228] =
    {   0,
      221,  221,  220,    3,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  222,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      223,  223,  223,  223,  223,  220,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  220,  220,  220,  220,  220,
      222,  220,  220,  220,  220,  220,  224,  223,  220,  223,
      220,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  220,  220,  220,  225,  226,
      223,  220,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  220,  220,  225,  227,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  227,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,    0,
      220,  220,  220,  220,  220,  220,  220
    } ;

static const flex_int16_t yy_nxt[770] =
    {   0,
      220,  220,    7,  220,    7,  100,    8,   49,    8,   53,
       79,    9,   50,    9,   48,   10,   11,   10,   11,   49,
       55,   59,   56,   57,   50,   57,   59,   59,   59,   57,
       61,   55,   59,   56,   57,   57,   57,   59,   59,   59,
       60,   97,   81,   97,   57,   57,   98,   59,   59,   57,
       57,   98,   59,  101,   12,   13,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   31,   33,   31,
       31,   31,   31,   31,   34,   31,   35,   31,   31,   31,
       36,   31,   31,   37,   38,   39,   40,   41,   31,   31,

       42,   31,   31,   31,   43,   44,   45,   31,   31,   31,
       31,   31,   46,   47,   57,   57,   57,   59,   59,   59,
       57,   57,   57,   59,   59,   59,   57,   57,   57,   59,
       59,   59,   57,   57,   57,   59,   59,   59,   57,   57,
       82,   59,   57,   63,   64,   59,   80,   52,   54,   68,
       62,   66,   65,   52,   71,   54,   67,   69,   48,  220,
      220,   75,   72,   78,   76,   77,   84,   70,   77,   73,
       74,  105,   76,   77,   83,   57,   77,   57,   59,  220,
       59,   76,   77,  220,   57,   57,   77,   59,   59,   76,
       77,  220,   57,   57,   77,   59,   59,   57,   57,   57,

       59,   59,   59,   57,   57,   85,   59,   59,   87,   57,
      220,   57,   59,   86,   59,   57,  220,  220,   59,   88,
       90,   78,   57,   57,  220,   59,   59,   95,  220,   89,
       76,   77,   91,  102,   77,  220,  103,  220,   92,   93,
       94,   57,   96,  104,   59,  220,   57,   76,   77,   59,
       57,   57,   77,   59,   59,   57,   57,  220,   59,   59,
      106,  220,  108,  220,   98,   57,   57,   57,   59,   59,
       59,  220,  109,  220,   77,  220,  111,   77,  107,  110,
      115,   57,   57,  117,   59,   59,  118,   57,  112,   57,
       59,   77,   59,  116,  220,   77,   57,  113,   57,   59,

       57,   59,   57,   59,   57,   59,   57,   59,  220,   59,
      120,  121,   57,  220,   57,   59,  119,   59,   57,  220,
      128,   59,  122,   57,   57,  126,   59,   59,   57,  220,
      124,   59,  125,   57,   57,  220,   59,   59,  123,  127,
       57,   57,  129,   59,   59,   57,   57,  220,   59,   59,
      130,  220,  132,   57,  131,   57,   59,   57,   59,  133,
       59,   57,  134,   57,   59,   57,   59,   57,   59,  136,
       59,  220,  135,  137,  140,   57,   57,  138,   59,   59,
       57,   57,  141,   59,   59,  139,   57,   57,  220,   59,
       59,  143,   57,  220,   57,   59,   57,   59,  220,   59,

      144,  142,   57,   57,  220,   59,   59,  145,  220,  220,
      220,   57,  147,  151,   59,  220,  154,  146,  148,  220,
       57,  220,  149,   59,  150,  156,  220,  152,  220,  155,
      153,  157,   57,   57,   57,   59,   59,   59,   57,   57,
      220,   59,   59,  158,   57,   57,   57,   59,   59,   59,
       57,   57,   57,   59,   59,   59,  160,   57,   57,  220,
       59,   59,   57,   57,  220,   59,   59,  159,   57,  220,
      166,   59,  161,  220,  220,  167,  162,  164,  220,   57,
      163,  169,   59,  165,   57,   57,  170,   59,   59,  220,
      168,  171,  172,   57,   57,   57,   59,   59,   59,   57,

       57,   57,   59,   59,   59,   57,   57,   57,   59,   59,
       59,   57,  174,   57,   59,  220,   59,  175,  178,  173,
       57,   57,   57,   59,   59,   59,  182,   57,  220,  220,
       59,  176,  177,   57,  220,  220,   59,  179,  180,  220,
       57,   57,  183,   59,   59,  185,  187,   57,  181,   57,
       59,  184,   59,   57,   57,  220,   59,   59,  186,  188,
       57,  191,  220,   59,   57,  189,   57,   59,   57,   59,
       57,   59,   57,   59,  220,   59,   57,  194,  190,   59,
       57,  220,   57,   59,  196,   59,  220,  192,  197,  193,
       57,   57,  195,   59,   59,  220,   57,  220,  198,   59,

      200,   57,   57,  220,   59,   59,  199,  220,   57,   57,
      201,   59,   59,   57,   57,  220,   59,   59,  203,  202,
       57,   57,  220,   59,   59,  204,   57,  220,  207,   59,
      209,  206,   57,  205,  220,   59,  208,  210,   57,   57,
       57,   59,   59,   59,   57,   57,  220,   59,   59,   57,
       57,   57,   59,   59,   59,   57,   57,  220,   59,   59,
      211,  212,  220,  220,  220,  220,  220,  213,  215,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  218,  216,
      220,  214,  220,  220,  217,  220,  220,  220,  220,  220,
      219,    6,    6,    6,    6,    6,   51,   51,   51,   51,

       51,   58,   58,   58,   58,   99,   99,  220,   99,  114,
      114,  114,    5,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220
    } ;

static const flex_int16_t yy_chk[770] =
    {   0,
        0,    0,    1,    0,    2,  226,    1,    9,    2,   20,
      224,    1,    9,    2,   20,    1,    1,    2,    2,   25,
       26,  114,   26,   31,   25,   32,   31,  100,   32,   33,
       33,   56,   33,   56,   58,   60,   71,   58,   60,   71,
       32,   76,   60,   76,   81,   90,   76,   81,   90,   93,
       99,   97,   93,   81,    1,    1,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,   34,   35,   37,   34,   35,   37,
       38,   39,   40,   38,   39,   40,   41,   42,   43,   41,
       42,   43,   44,   45,   62,   44,   45,   62,   86,   79,
       61,   86,   63,   35,   37,   63,   59,   51,   24,   39,
       34,   38,   37,   17,   42,   54,   38,   40,    8,    5,
        0,   45,   42,   55,   54,   54,   63,   41,   54,   43,
       44,   86,   55,   55,   62,   64,   55,   65,   64,    0,
       65,   54,   54,    0,   66,   67,   54,   66,   67,   55,
       55,    0,   68,   69,   55,   68,   69,   70,   72,   73,

       70,   72,   73,   75,   74,   64,   75,   74,   66,   84,
        0,   85,   84,   65,   85,   83,    0,    0,   83,   67,
       69,   78,   87,   89,    0,   87,   89,   75,    0,   68,
       78,   78,   70,   83,   78,    0,   84,    0,   72,   73,
       74,   88,   75,   85,   88,    0,   91,   78,   78,   91,
       94,   92,   78,   94,   92,   95,   96,    0,   95,   96,
       87,    0,   89,    0,   98,  102,  101,  103,  102,  101,
      103,    0,   91,    0,   98,    0,   94,   98,   88,   92,
      101,  104,  105,  103,  104,  105,  103,  106,   95,  107,
      106,   98,  107,  102,    0,   98,  108,   96,  109,  108,

      110,  109,  112,  110,  111,  112,  113,  111,    0,  113,
      105,  106,  115,    0,  117,  115,  104,  117,  116,    0,
      115,  116,  107,  118,  119,  112,  118,  119,  120,    0,
      110,  120,  111,  121,  122,    0,  121,  122,  109,  113,
      123,  124,  116,  123,  124,  127,  125,    0,  127,  125,
      117,    0,  120,  126,  118,  129,  126,  128,  129,  121,
      128,  130,  122,  131,  130,  132,  131,  133,  132,  124,
      133,    0,  123,  125,  128,  134,  135,  126,  134,  135,
      136,  137,  129,  136,  137,  127,  138,  139,    0,  138,
      139,  131,  140,    0,  143,  140,  142,  143,    0,  142,

      132,  130,  144,  145,    0,  144,  145,  133,    0,    0,
        0,  141,  135,  140,  141,    0,  142,  134,  136,    0,
      146,    0,  137,  146,  138,  144,    0,  141,    0,  143,
      141,  145,  147,  148,  149,  147,  148,  149,  150,  151,
        0,  150,  151,  146,  152,  154,  153,  152,  154,  153,
      155,  156,  157,  155,  156,  157,  148,  158,  159,    0,
      158,  159,  160,  161,    0,  160,  161,  147,  162,    0,
      155,  162,  149,    0,    0,  156,  150,  153,    0,  163,
      152,  158,  163,  154,  164,  165,  160,  164,  165,    0,
      157,  161,  162,  166,  167,  168,  166,  167,  168,  169,

      170,  171,  169,  170,  171,  172,  173,  174,  172,  173,
      174,  175,  164,  176,  175,    0,  176,  165,  168,  163,
      177,  179,  178,  177,  179,  178,  173,  180,    0,    0,
      180,  166,  167,  181,    0,    0,  181,  169,  170,    0,
      182,  183,  174,  182,  183,  176,  178,  184,  172,  185,
      184,  175,  185,  186,  187,    0,  186,  187,  177,  179,
      188,  183,    0,  188,  189,  180,  190,  189,  191,  190,
      193,  191,  192,  193,    0,  192,  194,  186,  182,  194,
      195,    0,  196,  195,  188,  196,    0,  184,  189,  185,
      197,  198,  187,  197,  198,    0,  199,    0,  190,  199,

      192,  200,  201,    0,  200,  201,  191,    0,  202,  204,
      193,  202,  204,  203,  205,    0,  203,  205,  195,  194,
      206,  207,    0,  206,  207,  196,  208,    0,  199,  208,
      201,  198,  209,  197,    0,  209,  200,  203,  210,  212,
      211,  210,  212,  211,  213,  214,    0,  213,  214,  215,
      216,  217,  215,  216,  217,  218,  219,    0,  218,  219,
      206,  207,    0,    0,    0,    0,    0,  209,  211,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  216,  212,
        0,  210,    0,    0,  215,    0,    0,    0,    0,    0,
      218,  221,  221,  221,  221,  221,  222,  222,  222,  222,

      222,  223,  223,  223,  223,  225,  225,    0,  225,  227,
      227,  227,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
#line 2 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
/*
 * black_box_l.l
 *
 *  Copyright by the COMMONWEALTH SCIENTIFIC AND INDUSTRIAL RESEARCH
 *  ORGANISATION (CSIRO), Australia.
 *  All rights reserved.
 *
 *  This file is part of ADT.  The full ADT copyright notice, including
 *  terms governing use, modification, and redistribution, is contained in
 *  the file COPYING. COPYING can be found at the root of the source code
 *  distribution tree;
 *
 * lex input file for black box definition parser. This parses black box
 * definitions for functions that are not to be differentiated with ADT.
 * These definitions are provided by our own simplfied syntax and then
 * translated into a form that tapenade understands. For example,
 * this is a definition in a Pascal comment field:
 *
 * {<
 *  D/D(.) INV(X+Y),
 *  D/D(X) .*X,
 *  D/D(Y) .*(1/Y);
 *  >}
 *
 * You can alos include a black box dependency specification with, for example,
 *
 * {<BLACKBOX ReadNotWritten:(1,0,0) NotReadThenWritten:(0,1,0) deps:(1,0,0,id,id);>}
 *
 * < and > symbols are used to indicate the start and end of a black box
 * definition and must be supplied for inline definitions. This allows the
 * black box definition to be embedded within existing comments and not break
 * the parsing of the definition.
 */


#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "lexer.h"
#include "adtutils.hpp"
#include "adtblackbox.hpp"


#if defined(_MSC_VER)
  #include <io.h>

  #define isatty _isatty

  #pragma warning(disable : 4996)
#else
  #include <unistd.h>
#endif


#define TOKEN_KEYWORD       0
#define TOKEN_NUMBER_FIXED  1
#define TOKEN_NUMBER_FLOAT  2
#define TOKEN_TEXT          3


#define YYSTYPE   blackBoxType


#include "black_box_y.h"


int         yyBlackBoxdebug           = 0;
int         yyBlackBoxIsFile          = 0;
int         yyBlackBoxReentrancyCount = 0;
int         adtBlackBox_nError        = 0;
const char* adtBlackBox_pErrorMsg     = 0;
int         adtBlackBox_nLineNumber   = 1;
const char* adtBlackBox_pFileName     = "";
void*       adtBlackBox_pContext      = 0;
char        sTempBuffer[1024]         = {0};


static int input();


void yyBlackBox_endParse(void)
{
  yy_flush_buffer(YY_CURRENT_BUFFER);
}


void yyBlackBox_releaseBuffer(void)
{
  yy_delete_buffer(YY_CURRENT_BUFFER);
}


int yyBlackBox_lineNumber(void)
{
  return (adtBlackBox_nLineNumber);
}


const char* yyBlackBox_fileName(void)
{
  return (adtBlackBox_pFileName);
}


void yyBlackBox_resetLineNumber(const char* pFileName)
{
  adtBlackBox_nError        = 0;
  adtBlackBox_pErrorMsg     = 0;
  adtBlackBox_nLineNumber   = 1;
  adtBlackBox_pFileName     = "";
  yyBlackBoxIsFile          = 0;
  yyBlackBoxReentrancyCount = 0;

  if (pFileName)
  {
    adtBlackBox_pFileName = pFileName;
    yyBlackBoxIsFile      = 1;
  }
}


int yyBlackBox_error(void)
{
  return (adtBlackBox_nError);
}


const char* yyBlackBox_errorMsg(void)
{
  return (adtBlackBox_pErrorMsg);
}


void yyBlackBoxerror(char const* sErrorMessage)
{
  if (adtBlackBox_pFileName != 0)
  {
    printf("BLACK BOX COMPILE ERROR on line %d in file %s : %s\n", adtBlackBox_nLineNumber, adtBlackBox_pFileName, sErrorMessage);
  }

  adtBlackBox_nError    = 1;
  adtBlackBox_pErrorMsg = adtBlackBox_AllocString(adtBlackBox_pContext, sErrorMessage);
}


int dispatchToken(void* pContext, YYSTYPE* p_yylval, const char* pTokenText, int nType, int nToken)
{
  if (p_yylval != 0)
  {
    p_yylval->pContext  = pContext;
    p_yylval->dValue    = 0.0;
    p_yylval->nValue    = 0;
    p_yylval->sValue    = 0;

    switch (nType)
    {
      case TOKEN_KEYWORD:
      {
        p_yylval->sValue = adtBlackBox_AllocString(pContext, pTokenText);
        break;
      }

      case TOKEN_NUMBER_FIXED:
      {
        p_yylval->sValue = adtBlackBox_AllocString(pContext, pTokenText);
        p_yylval->nValue = atoi(pTokenText);
        break;
      }

      case TOKEN_NUMBER_FLOAT:
      {
        p_yylval->sValue = adtBlackBox_AllocString(pContext, pTokenText);
        p_yylval->dValue = atof(pTokenText);
        break;
      }

      case TOKEN_TEXT:
      default:
      {
        break;
      }
    }
  }

  return (nToken);
}


#line 873 "..\\src\\black_box_l.c"

#line 875 "..\\src\\black_box_l.c"

#define INITIAL 0
#define BLACKBOXDEF 1

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 202 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"

#line 1097 "..\\src\\black_box_l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 221 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 713 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 203 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          yyBlackBox_push_state(BLACKBOXDEF);
                                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 208 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          yyBlackBox_pop_state();
                                        }
	YY_BREAK
/* tokenise comment delimiters and ignore them. This has the effect of treating the entire
                                           comment block less the comment delimiters as a command field to be parsed */
case 3:
YY_RULE_SETUP
#line 215 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 216 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 217 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 218 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 219 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
/* single line comment. This allows comments in standalone definition files */
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 222 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          adtBlackBox_nLineNumber++;
                                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 227 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, FUNCTION));
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 228 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, PROCEDURE));
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 229 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, RESULT));
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 230 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, IN));
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 231 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, OUT));
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 232 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, F_BEGIN));
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 233 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, F_END));
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 234 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, REAL));
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 235 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, INTEGER));
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 236 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COMPLEX));
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 237 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, CHARACTER));
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 238 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, BOOLEAN));
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 239 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, REAL_ARRAY));
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 240 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, INTEGER_ARRAY));
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 241 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COMPLEX_ARRAY));
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 242 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, CHARACTER_ARRAY));
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 243 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, BOOLEAN_ARRAY));
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 244 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, BLACKBOX));
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 245 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, READ_NOT_WRITTEN));
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 246 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, NOT_READ_THEN_WRITTEN));
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 247 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, NOT_READ_NOT_WRITTEN));
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 248 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, READ_THEN_WRITTEN));
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 249 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, DEPS));
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 250 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, DERIV_OP));
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 251 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, ID));
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 252 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COLON));
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 253 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, SEMICOLON));
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 254 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COMMA));
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 255 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, LBRACKET));
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 256 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, RBRACKET));
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 257 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, PLUS));
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 258 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, MINUS));
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 259 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, MULTIPLY));
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 260 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, POWER));
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 261 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, POWER));
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 262 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, DIVIDE));
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 263 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, PERIOD));
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 264 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, IDENTIFIER));
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 265 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, QUALIFIED_IDENTIFIER));
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 266 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_NUMBER_FIXED, NUMBER_FIXED));
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 267 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_NUMBER_FLOAT, NUMBER_FLOAT));
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 269 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                        }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 273 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          adtBlackBox_nLineNumber++;
                                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 278 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);

                                          sprintf(sTempBuffer, "illegal character '%c' (0x%x) in black box definition", yytext[0], yytext[0]);

                                          adtBlackBox_nError    = 1;
                                          adtBlackBox_pErrorMsg = adtBlackBox_AllocString(adtBlackBox_pContext, sTempBuffer);
                                        }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 287 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          adtBlackBox_nLineNumber++;
                                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 292 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 295 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"
ECHO;
	YY_BREAK
#line 1461 "..\\src\\black_box_l.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLACKBOXDEF):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 221 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 221 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 220);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 295 "C:\\cygwin\\usr\\src\\adt\\src\\black_box_l.l"



int yywrap()
{
  return (1);
}


void yyBlackBox_pushState(int nState)
{
  yyBlackBox_push_state(nState);
}


void yyBlackBox_popState(void)
{
  yyBlackBox_pop_state();
}


int yyBlackBox_topState(void)
{
  return (yyBlackBox_top_state());
}

