
#line 2 "../../src/black_box_l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[217] =
    {   0,
        0,    0,    0,    0,   56,   54,   53,   54,   54,    1,
        2,    3,    4,   52,   50,   51,   52,   37,   38,   41,
       39,   36,   40,   45,   44,   48,   34,   35,    1,    2,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   43,    3,    4,    6,    5,    7,    0,    8,   42,
       49,   49,   48,    0,   46,    0,   46,   46,   46,   46,
       46,    0,   46,   46,   46,   33,   12,   46,   46,   46,
       46,    0,   49,   49,   49,   47,    0,   46,   46,   46,
       46,   46,   32,   46,   15,   46,   46,   46,   13,   46,
       46,   46,    0,   49,   47,   47,   46,   46,   46,   46,

       46,   31,   46,   46,   46,   46,   46,   16,   46,   47,
       14,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   11,   46,   20,   46,   18,   46,
       17,   46,   46,   46,   46,   46,   26,   46,   46,   46,
        9,   46,   46,   46,   46,   46,   46,   46,   46,   19,
       46,   46,   46,   46,   10,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   21,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   25,   46,   23,   22,   46,   46,   46,

       46,   46,   46,   46,   27,   46,   24,   46,   46,   30,
       46,   46,   29,   46,   28,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
        1,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       27,   34,   35,   36,   37,   27,   38,   39,   40,   27,
        1,    1,    1,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   27,   52,   53,   54,   55,
       56,   57,   27,   58,   59,   60,   61,   27,   62,   63,
       64,   27,   65,    1,   66,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    3,    4,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1
    } ;

static const flex_int16_t yy_base[224] =
    {   0,
        0,    2,   68,    0,  190,  888,  888,  173,    1,  888,
      888,  888,  888,  888,  888,  888,  167,  888,  888,    3,
      888,  888,  888,  152,   13,   10,  888,  888,  888,  888,
       13,  124,  125,   17,  129,  130,  137,  131,  141,  148,
      150,  888,  888,  888,  888,  888,  888,  151,  888,  888,
      166,  181,   19,    0,   22,  135,  162,  182,  194,  198,
      206,    1,  204,  210,  216,   23,  221,  228,  229,  234,
      235,   30,  888,  888,  245,  136,    0,  258,  262,  248,
      241,  269,  888,  286,   30,  292,  294,  299,   31,  303,
      313,  314,  124,  307,   51,   21,  308,  304,  324,  329,

      338,   35,  347,  354,  359,  363,  365,  373,  375,   12,
       37,  155,  379,  388,  402,  400,  407,  416,  398,  421,
      425,  427,  426,  432,  441,  446,  384,  447,  455,  462,
      454,  473,  479,  460,   39,  481,  486,  488,  500,  467,
      505,  493,  516,  520,  525,  526,   41,  527,  532,  543,
       43,  551,  541,  553,  557,  561,  574,  578,  588,  587,
      594,  596,  595,  602,   45,  600,  604,  621,  606,  623,
      631,  633,  639,  645,  646,  657,   47,  661,  659,  670,
      676,  681,  685,  691,  696,  698,  700,  710,  714,  715,
      719,  726,  731,   49,  741,  187,  240,  732,  746,  750,

      765,  769,  771,  775,  339,  779,  784,  792,  785,  790,
      805,  804,  806,  811,  813,  888,  866,  871,  875,    6,
      879,    1,  882
    } ;

static const flex_int16_t yy_def[224] =
    {   0,
      217,  217,  216,    3,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  218,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  216,  216,  216,  216,  216,  216,  218,  216,  216,
      216,  216,  216,  220,  219,  216,  219,  219,  219,  219,
      219,  216,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  216,  216,  216,  216,  221,  222,  219,  219,  219,
      219,  219,  216,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  216,  216,  221,  223,  219,  219,  219,  219,

      219,  219,  219,  219,  219,  219,  219,  219,  219,  223,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,

      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  219,    0,  216,  216,  216,  216,
      216,  216,  216
    } ;

static const flex_int16_t yy_nxt[955] =
    {   0,
      216,  216,    7,  216,    7,   96,    8,   46,    8,   50,
       76,    9,   47,    9,   45,   10,   11,   10,   11,   46,
       52,   83,   53,   54,   47,   56,   56,   54,   62,   52,
       56,   53,   54,   54,   56,   56,   56,   93,   63,   93,
       54,   54,   94,   56,   56,   54,   83,   54,   56,   54,
       56,   54,   56,   54,   56,   54,   56,   54,   56,   54,
       56,   54,   56,   63,   12,   13,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   31,   31,   37,   31,   31,   31,   31,   38,   39,

       40,   41,   31,   31,   31,   31,   31,   31,   42,   31,
       31,   32,   33,   34,   35,   36,   31,   31,   37,   31,
       31,   31,   38,   39,   40,   41,   31,   31,   31,   31,
       31,   31,   43,   44,   54,   54,   94,   56,   56,   54,
       54,   54,   56,   56,   56,   57,   54,   54,   77,   60,
       56,   54,   58,   49,   56,   59,   61,   66,   54,   64,
       54,   56,   68,   56,   51,   54,   65,   67,   56,   49,
       57,   71,   54,  124,   60,   56,   58,   69,   51,   59,
       61,   70,   66,   64,   45,   78,   68,   72,   73,  216,
       65,   67,   54,   75,   74,   56,   71,   54,  124,   79,

       56,   69,   72,   73,   54,   70,  216,   56,   54,   74,
       78,   56,   72,   73,   54,   81,   54,   56,   74,   56,
       54,  216,  216,   56,   79,   80,   54,   72,   73,   56,
       85,   54,  216,   74,   56,   82,   84,  216,   54,   54,
       81,   56,   56,  216,   54,   54,   86,   56,   56,   80,
       54,   54,   91,   56,   56,   85,   87,   75,   54,   82,
       84,   56,  216,   88,   89,   90,   72,   73,   54,   92,
       86,   56,   54,   74,  100,   56,   99,   91,  216,   54,
       87,   98,   56,   97,  216,  216,  216,   88,   89,   90,
      216,   72,   73,   92,  216,  216,   54,   74,  100,   56,

       99,  101,   54,  216,   54,   56,   98,   56,   97,   54,
      216,  103,   56,   54,   54,  104,   56,   56,   54,   94,
      102,   56,  106,   54,   54,  101,   56,   56,  216,   73,
      216,  112,  105,  107,   54,   74,  103,   56,  111,   54,
      104,  108,   56,  216,  102,  113,  114,  106,   54,   54,
      109,   56,   56,  216,   73,  112,  105,   54,  107,   74,
       56,  216,  111,  216,   54,  108,  115,   56,  216,   54,
      113,  114,   56,   54,  109,   54,   56,  117,   56,  216,
      118,  216,  116,   54,  119,   54,   56,  216,   56,   54,
      115,  216,   56,  216,   54,  120,  125,   56,   54,  216,

      121,   56,  117,  123,  216,  118,  116,  126,   54,  119,
       54,   56,   54,   56,  122,   56,  216,   54,  131,  120,
       56,  125,  139,  127,  121,  128,   54,  123,  129,   56,
      216,   54,  126,  130,   56,   54,   54,   54,   56,   56,
       56,  216,   54,  131,  134,   56,  139,  216,  127,  133,
      128,   54,  132,  129,   56,  216,   54,   54,  130,   56,
       56,  135,  216,  136,   54,   54,  216,   56,   56,  134,
       54,  137,   54,   56,  133,   56,  132,   54,  140,  216,
       56,  138,  142,   54,  216,  135,   56,  136,  141,   54,
      143,   54,   56,  146,   56,  137,   54,  151,   54,   56,

      145,   56,  140,   54,  216,  138,   56,  142,  144,  149,
       54,  216,  141,   56,  143,   54,  216,  146,   56,  147,
      216,  151,  216,  153,  216,  145,   54,  148,  154,   56,
       54,  216,  144,   56,  149,   54,   54,   54,   56,   56,
       56,  150,   54,  147,  159,   56,  152,  153,  216,  155,
      216,   54,  154,   54,   56,  157,   56,  156,  216,  158,
      161,   54,  216,   54,   56,  160,   56,   54,  162,  159,
       56,   54,  163,  155,   56,  216,  216,  164,  165,  157,
      216,  156,  216,  158,   54,  161,  216,   56,   54,  160,
      216,   56,  216,  162,  166,  168,  163,   54,   54,  216,

       56,   56,  164,  165,   54,   54,   54,   56,   56,   56,
       54,  167,   54,   56,   54,   56,   54,   56,  166,   56,
      168,  169,  216,  174,  216,  175,  216,  171,  170,  172,
      173,   54,  216,   54,   56,  167,   56,  176,  216,  178,
      179,   54,  216,   54,   56,  169,   56,  216,  174,   54,
      175,  171,   56,  172,  173,   54,   54,  216,   56,   56,
      177,  176,  216,  178,  180,  179,  181,   54,  216,   54,
       56,   54,   56,  216,   56,  183,  182,  216,  186,  216,
       54,  184,  185,   56,  177,  216,   54,  188,  180,   56,
      181,   54,  187,  189,   56,   54,  216,  216,   56,  183,

      182,   54,  216,  186,   56,  184,   54,  185,   54,   56,
       54,   56,  188,   56,  190,  216,  187,  216,  189,  216,
       54,  216,  191,   56,   54,   54,  192,   56,   56,   54,
      216,  193,   56,  195,  216,  216,   54,  194,  190,   56,
      198,   54,   54,  216,   56,   56,  191,  200,  216,  196,
      192,   54,  199,  197,   56,  193,   54,  195,  202,   56,
       54,  194,  216,   56,  216,  198,  201,  203,  216,  216,
      216,  204,  200,  196,  216,   54,  199,  197,   56,   54,
      205,   54,   56,  202,   56,   54,  206,  216,   56,   54,
      201,  203,   56,  216,   54,   54,  204,   56,   56,  216,

       54,  216,   54,   56,  205,   56,  208,  216,  207,  210,
      209,  206,  216,  211,   54,   54,   54,   56,   56,   56,
      212,   54,  216,   54,   56,  214,   56,  216,  216,  216,
      208,  216,  207,  210,  209,  213,  216,  216,  211,  216,
      216,  215,  216,  216,  212,  216,  216,  216,  216,  216,
      214,  216,  216,  216,  216,  216,  216,  216,  216,  213,
      216,  216,  216,  216,  216,  215,    6,    6,    6,    6,
        6,   48,   48,   48,   48,   48,   55,   55,   55,   55,
       95,   95,  216,   95,  110,  110,  110,    5,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216
    } ;

static const flex_int16_t yy_chk[955] =
    {   0,
        0,    0,    1,    0,    2,  222,    1,    9,    2,   20,
      220,    1,    9,    2,   20,    1,    1,    2,    2,   25,
       26,   62,   26,   31,   25,  110,   31,   34,   34,   53,
       34,   53,   55,   66,   96,   55,   66,   72,   34,   72,
       85,   89,   72,   85,   89,  102,   62,  111,  102,  135,
      111,  147,  135,  151,  147,  165,  151,  177,  165,  194,
      177,   95,  194,   34,    1,    1,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,   32,   33,   93,   32,   33,   35,
       36,   38,   35,   36,   38,   32,   76,   37,   56,   33,
       37,   39,   32,   48,   39,   32,   33,   37,   40,   35,
       41,   40,   38,   41,   24,  112,   36,   37,  112,   17,
       32,   41,   57,  112,   33,   57,   32,   39,   51,   32,
       33,   40,   37,   35,    8,   57,   38,   51,   51,    5,
       36,   37,   58,   52,   51,   58,   41,  196,  112,   58,

      196,   39,   52,   52,   59,   40,    0,   59,   60,   52,
       57,   60,   51,   51,   63,   60,   61,   63,   51,   61,
       64,    0,    0,   64,   58,   59,   65,   52,   52,   65,
       64,   67,    0,   52,   67,   61,   63,    0,   68,   69,
       60,   68,   69,    0,   70,   71,   65,   70,   71,   59,
      197,   81,   71,  197,   81,   64,   67,   75,   80,   61,
       63,   80,    0,   68,   69,   70,   75,   75,   78,   71,
       65,   78,   79,   75,   81,   79,   80,   71,    0,   82,
       67,   79,   82,   78,    0,    0,    0,   68,   69,   70,
        0,   75,   75,   71,    0,    0,   84,   75,   81,   84,

       80,   82,   86,    0,   87,   86,   79,   87,   78,   88,
        0,   86,   88,   90,   98,   87,   90,   98,   97,   94,
       84,   97,   90,   91,   92,   82,   91,   92,    0,   94,
        0,   98,   88,   91,   99,   94,   86,   99,   97,  100,
       87,   91,  100,    0,   84,   99,  100,   90,  101,  205,
       92,  101,  205,    0,   94,   98,   88,  103,   91,   94,
      103,    0,   97,    0,  104,   91,  101,  104,    0,  105,
       99,  100,  105,  106,   92,  107,  106,  104,  107,    0,
      105,    0,  103,  108,  106,  109,  108,    0,  109,  113,
      101,    0,  113,    0,  127,  107,  113,  127,  114,    0,

      107,  114,  104,  109,    0,  105,  103,  114,  119,  106,
      116,  119,  115,  116,  108,  115,    0,  117,  119,  107,
      117,  113,  127,  115,  107,  116,  118,  109,  117,  118,
        0,  120,  114,  118,  120,  121,  123,  122,  121,  123,
      122,    0,  124,  119,  122,  124,  127,    0,  115,  121,
      116,  125,  120,  117,  125,    0,  126,  128,  118,  126,
      128,  123,    0,  124,  131,  129,    0,  131,  129,  122,
      134,  125,  130,  134,  121,  130,  120,  140,  128,    0,
      140,  126,  130,  132,    0,  123,  132,  124,  129,  133,
      131,  136,  133,  134,  136,  125,  137,  140,  138,  137,

      133,  138,  128,  142,    0,  126,  142,  130,  132,  138,
      139,    0,  129,  139,  131,  141,    0,  134,  141,  136,
        0,  140,    0,  142,    0,  133,  143,  137,  142,  143,
      144,    0,  132,  144,  138,  145,  146,  148,  145,  146,
      148,  139,  149,  136,  148,  149,  141,  142,    0,  143,
        0,  153,  142,  150,  153,  145,  150,  144,    0,  146,
      150,  152,    0,  154,  152,  149,  154,  155,  152,  148,
      155,  156,  153,  143,  156,    0,    0,  154,  155,  145,
        0,  144,    0,  146,  157,  150,    0,  157,  158,  149,
        0,  158,    0,  152,  156,  158,  153,  160,  159,    0,

      160,  159,  154,  155,  161,  163,  162,  161,  163,  162,
      166,  157,  164,  166,  167,  164,  169,  167,  156,  169,
      158,  159,    0,  164,    0,  166,    0,  161,  160,  162,
      163,  168,    0,  170,  168,  157,  170,  167,    0,  169,
      170,  171,    0,  172,  171,  159,  172,    0,  164,  173,
      166,  161,  173,  162,  163,  174,  175,    0,  174,  175,
      168,  167,    0,  169,  171,  170,  172,  176,    0,  179,
      176,  178,  179,    0,  178,  174,  173,    0,  178,    0,
      180,  175,  176,  180,  168,    0,  181,  180,  171,  181,
      172,  182,  179,  181,  182,  183,    0,    0,  183,  174,

      173,  184,    0,  178,  184,  175,  185,  176,  186,  185,
      187,  186,  180,  187,  182,    0,  179,    0,  181,    0,
      188,    0,  183,  188,  189,  190,  184,  189,  190,  191,
        0,  185,  191,  187,    0,    0,  192,  186,  182,  192,
      190,  193,  198,    0,  193,  198,  183,  192,    0,  188,
      184,  195,  191,  189,  195,  185,  199,  187,  195,  199,
      200,  186,    0,  200,    0,  190,  193,  198,    0,    0,
        0,  199,  192,  188,    0,  201,  191,  189,  201,  202,
      200,  203,  202,  195,  203,  204,  201,    0,  204,  206,
      193,  198,  206,    0,  207,  209,  199,  207,  209,    0,

      210,    0,  208,  210,  200,  208,  203,    0,  202,  206,
      204,  201,    0,  208,  212,  211,  213,  212,  211,  213,
      209,  214,    0,  215,  214,  212,  215,    0,    0,    0,
      203,    0,  202,  206,  204,  211,    0,    0,  208,    0,
        0,  214,    0,    0,  209,    0,    0,    0,    0,    0,
      212,    0,    0,    0,    0,    0,    0,    0,    0,  211,
        0,    0,    0,    0,    0,  214,  217,  217,  217,  217,
      217,  218,  218,  218,  218,  218,  219,  219,  219,  219,
      221,  221,    0,  221,  223,  223,  223,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "black_box_l.l"
#line 2 "black_box_l.l"
/*
 * black_box_l.l
 *
 *  Copyright by the COMMONWEALTH SCIENTIFIC AND INDUSTRIAL RESEARCH
 *  ORGANISATION (CSIRO), Australia.
 *  All rights reserved.
 *
 *  This file is part of ADT.  The full ADT copyright notice, including
 *  terms governing use, modification, and redistribution, is contained in
 *  the file COPYING. COPYING can be found at the root of the source code
 *  distribution tree;
 *
 * lex input file for black box definition parser. This parses black box
 * definitions for functions that are not to be differentiated with ADT.
 * These definitions are provided by our own simplfied syntax and then
 * translated into a form that tapenade understands. For example,
 * this is a definition in a Pascal comment field:
 *
 * {<
 *  D/D(.) INV(X+Y),
 *  D/D(X) .*X,
 *  D/D(Y) .*(1/Y);
 *  >}
 *
 * You can alos include a black box dependency specification with, for example,
 *
 * {<BLACKBOX ReadNotWritten:(1,0,0) NotReadThenWritten:(0,1,0) deps:(1,0,0,id,id);>}
 *
 * < and > symbols are used to indicate the start and end of a black box
 * definition and must be supplied for inline definitions. This allows the
 * black box definition to be embedded within existing comments and not break
 * the parsing of the definition.
 */


#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "lexer.h"
#include "adtutils.hpp"
#include "adtblackbox.hpp"


#if defined(_MSC_VER)
  #include <io.h>

  #define isatty _isatty

  #pragma warning(disable : 4996)
#else
  #include <unistd.h>
#endif


#define TOKEN_KEYWORD       0
#define TOKEN_NUMBER_FIXED  1
#define TOKEN_NUMBER_FLOAT  2
#define TOKEN_TEXT          3


#define YYSTYPE   blackBoxType


#include "black_box_y.h"


#if defined(_MSC_VER)
int         yyBlackBoxdebug           = 0;
#endif
int         yyBlackBoxIsFile          = 0;
int         yyBlackBoxReentrancyCount = 0;
int         adtBlackBox_nError        = 0;
const char* adtBlackBox_pErrorMsg     = 0;
int         adtBlackBox_nLineNumber   = 1;
const char* adtBlackBox_pFileName     = "";
void*       adtBlackBox_pContext      = 0;
char        sTempBuffer[1024]         = {0};


static int input();


void yyBlackBox_endParse(void)
{
  yy_flush_buffer(YY_CURRENT_BUFFER);
}


void yyBlackBox_releaseBuffer(void)
{
  yy_delete_buffer(YY_CURRENT_BUFFER);
}


int yyBlackBox_lineNumber(void)
{
  return (adtBlackBox_nLineNumber);
}


const char* yyBlackBox_fileName(void)
{
  return (adtBlackBox_pFileName);
}


void yyBlackBox_resetLineNumber(const char* pFileName)
{
  adtBlackBox_nError        = 0;
  adtBlackBox_pErrorMsg     = 0;
  adtBlackBox_nLineNumber   = 1;
  adtBlackBox_pFileName     = "";
  yyBlackBoxIsFile          = 0;
  yyBlackBoxReentrancyCount = 0;

  if (pFileName)
  {
    adtBlackBox_pFileName = pFileName;
    yyBlackBoxIsFile      = 1;
  }
}


int yyBlackBox_error(void)
{
  return (adtBlackBox_nError);
}


const char* yyBlackBox_errorMsg(void)
{
  return (adtBlackBox_pErrorMsg);
}


void yyBlackBoxerror(char const* sErrorMessage)
{
  if (adtBlackBox_pFileName != 0)
  {
    printf("BLACK BOX COMPILE ERROR on line %d in file %s : %s\n", adtBlackBox_nLineNumber, adtBlackBox_pFileName, sErrorMessage);
  }

  adtBlackBox_nError    = 1;
  adtBlackBox_pErrorMsg = adtBlackBox_AllocString(adtBlackBox_pContext, sErrorMessage);
}


int dispatchToken(void* pContext, YYSTYPE* p_yylval, const char* pTokenText, int nType, int nToken)
{
  if (p_yylval != 0)
  {
    p_yylval->pContext  = pContext;
    p_yylval->dValue    = 0.0;
    p_yylval->nValue    = 0;
    p_yylval->sValue    = 0;

    switch (nType)
    {
      case TOKEN_KEYWORD:
      {
        p_yylval->sValue = adtBlackBox_AllocString(pContext, pTokenText);
        break;
      }

      case TOKEN_NUMBER_FIXED:
      {
        p_yylval->sValue = adtBlackBox_AllocString(pContext, pTokenText);
        p_yylval->nValue = atoi(pTokenText);
        break;
      }

      case TOKEN_NUMBER_FLOAT:
      {
        p_yylval->sValue = adtBlackBox_AllocString(pContext, pTokenText);
        p_yylval->dValue = atof(pTokenText);
        break;
      }

      case TOKEN_TEXT:
      default:
      {
        break;
      }
    }
  }

  return (nToken);
}


#line 917 "../../src/black_box_l.c"

#line 919 "../../src/black_box_l.c"

#define INITIAL 0
#define BLACKBOXDEF 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 204 "black_box_l.l"

#line 1149 "../../src/black_box_l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 217 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 888 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 205 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          yyBlackBox_push_state(BLACKBOXDEF);
                                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 210 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          yyBlackBox_pop_state();
                                        }
	YY_BREAK
/* tokenise comment delimiters and ignore them. This has the effect of treating the entire
                                           comment block less the comment delimiters as a command field to be parsed */
case 3:
YY_RULE_SETUP
#line 217 "black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 218 "black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 219 "black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 220 "black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 221 "black_box_l.l"
{dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);}
	YY_BREAK
/* single line comment. This allows comments in standalone definition files */
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 224 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          adtBlackBox_nLineNumber++;
                                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 229 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, FUNCTION));
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 230 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, PROCEDURE));
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 231 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, RESULT));
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 232 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, IN));
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 233 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, OUT));
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 234 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, F_BEGIN));
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 235 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, F_END));
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 236 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, REAL));
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 237 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, INTEGER));
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 238 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COMPLEX));
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 239 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, CHARACTER));
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 240 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, BOOLEAN));
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 241 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, REAL_ARRAY));
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 242 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, INTEGER_ARRAY));
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 243 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COMPLEX_ARRAY));
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 244 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, CHARACTER_ARRAY));
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 245 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, BOOLEAN_ARRAY));
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 246 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, BLACKBOX));
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 247 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, READ_NOT_WRITTEN));
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 248 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, NOT_READ_THEN_WRITTEN));
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 249 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, NOT_READ_NOT_WRITTEN));
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 250 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, READ_THEN_WRITTEN));
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 251 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, DEPS));
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 252 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, DERIV_OP));
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 253 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, ID));
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 254 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COLON));
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 255 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, SEMICOLON));
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 256 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, COMMA));
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 257 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, LBRACKET));
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 258 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, RBRACKET));
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 259 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, PLUS));
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 260 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, MINUS));
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 261 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, MULTIPLY));
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 262 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, POWER));
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 263 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, POWER));
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 264 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, DIVIDE));
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 265 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, PERIOD));
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 266 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, IDENTIFIER));
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 267 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_KEYWORD, QUALIFIED_IDENTIFIER));
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 268 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_NUMBER_FIXED, NUMBER_FIXED));
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 269 "black_box_l.l"
return (dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_NUMBER_FLOAT, NUMBER_FLOAT));
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 271 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                        }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 275 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          adtBlackBox_nLineNumber++;
                                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 280 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);

                                          sprintf(sTempBuffer, "illegal character '%c' (0x%x) in black box definition", yytext[0], yytext[0]);

                                          adtBlackBox_nError    = 1;
                                          adtBlackBox_pErrorMsg = adtBlackBox_AllocString(adtBlackBox_pContext, sTempBuffer);
                                        }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 289 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                          adtBlackBox_nLineNumber++;
                                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 294 "black_box_l.l"
{
                                          dispatchToken(adtBlackBox_pContext, &yylval, yytext, TOKEN_TEXT, -1);
                                        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 297 "black_box_l.l"
ECHO;
	YY_BREAK
#line 1513 "../../src/black_box_l.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLACKBOXDEF):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 217 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 217 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 216);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 297 "black_box_l.l"



int yywrap()
{
  return (1);
}


void yyBlackBox_pushState(int nState)
{
  yyBlackBox_push_state(nState);
}


void yyBlackBox_popState(void)
{
  yyBlackBox_pop_state();
}


int yyBlackBox_topState(void)
{
  return (yyBlackBox_top_state());
}

