#line 1 "..\\src\\java_l.c"

#line 3 "..\\src\\java_l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[331] =
    {   0,
        0,    0,    1,    1,  116,  114,  113,  112,   90,  114,
      114,   96,   89,  114,   84,   85,   94,   93,   81,   92,
       88,   95,  106,  106,   82,   78,   97,   83,   98,  101,
      103,   86,   87,   99,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,   79,
      100,   80,   91,    1,    1,    1,  115,   77,    0,  111,
        0,    0,    2,   63,   72,   64,    0,    0,   61,   70,
       59,   71,   60,  108,    4,    0,   62,  109,  105,    0,
        0,  106,  102,   69,   74,   76,   75,   68,  103,   65,
      103,  103,  103,  103,  103,  103,  103,  103,  103,   18,

      103,  103,  103,  103,  103,  103,   26,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,   66,   73,    1,    1,
        1,  110,  108,    0,    3,    0,    5,  108,  109,    0,
        0,  107,  104,   58,   57,   67,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,   25,  103,  103,   31,  103,  103,   34,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,   49,  103,  103,  103,    0,  108,
      108,    0,    0,  109,  107,   56,  103,    7,  103,   10,

       11,  103,   13,  103,  103,  103,  103,  103,   20,  103,
      103,  103,  103,  103,  103,  103,  103,   32,  103,   55,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
       45,  103,  103,   53,   50,  103,  103,    0,  108,  103,
      103,    9,   12,   14,   15,  103,  103,  103,  103,   54,
       23,   24,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,   40,  103,   42,  103,  103,   46,  103,  103,
       52,  103,  103,  103,  103,   19,  103,  103,  103,   28,
      103,  103,   33,  103,  103,  103,   36,   39,   41,   43,
      103,   47,  103,  103,  103,    8,  103,   17,   21,   22,

      103,  103,  103,   35,   37,  103,  103,  103,  103,    6,
       16,  103,  103,  103,  103,  103,  103,   51,  103,  103,
       29,   38,  103,   48,   27,   30,  103,  103,   44,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   27,   28,   29,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   31,   30,   30,
       32,   33,   34,   35,   30,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   30,   45,   46,   47,   48,
       49,   50,   30,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    5,
        5,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    2,
        1,    2,    1
    } ;

static const flex_int16_t yy_base[340] =
    {   0,
        0,    0,   61,   62,  462,  463,  463,  463,  438,   61,
      457,  436,   61,  425,  463,  463,  434,   57,  463,   58,
       53,   65,   71,   67,  436,  463,   52,  432,   68,  463,
        0,  463,  463,  431,  416,   47,   57,   61,   51,   68,
       68,  403,   89,   82,  411,   84,   83,  401,  406,  463,
       90,  463,  463,    0,  116,  436,  463,  463,  115,  463,
      444,  443,  463,  463,  463,  463,  121,  132,  463,  463,
      463,  463,  463,  128,  438,  441,  463,  131,  145,  162,
        0,  168,  463,  420,  463,  463,  463,  108,    0,  463,
      390,  392,  400,  386,   92,  402,  401,  388,  394,  380,

      381,  379,  385,  382,  380,  377,    0,  377,  100,  378,
      372,  368,  377,  384,  130,  384,  367,  370,  382,  367,
      372,  367,  138,  147,  144,  370,  463,  463,    0,  159,
        0,  463,  463,  179,  463,  410,  463,  184,  463,  191,
      147,  199,    0,  463,  463,  389,  358,  364,  373,  368,
      367,  368,  354,  352,  147,  367,  365,  361,  360,  347,
      362,  361,    0,  181,  343,  355,  352,  349,    0,  346,
      346,  335,  336,  342,  333,  335,  332,  344,  330,  344,
      329,  331,  331,  338,    0,  338,  340,  329,  196,  214,
      463,  216,  218,  227,  463,  463,  323,  333,  327,    0,

        0,  328,    0,  318,  316,  324,  313,  320,    0,  317,
      324,  317,  309,  321,  309,  323,  307,    0,  302,    0,
      320,  319,  314,  309,  301,  298,  306,  298,  310,  304,
        0,  290,  293,    0,    0,  291,  303,  229,  231,  306,
      305,    0,    0,    0,    0,  292,  293,  298,  298,    0,
      290,    0,  288,  281,  285,  291,  291,  288,  276,  290,
      289,  278,    0,  287,    0,  281,  272,  270,  277,  276,
        0,  281,  270,  263,  263,    0,  263,  256,  273,    0,
      274,  275,    0,  270,  256,  237,    0,    0,    0,    0,
      222,    0,  229,  221,  212,    0,  224,    0,    0,    0,

      215,  222,  223,    0,    0,  219,  209,  204,  211,    0,
        0,  191,  193,  199,  183,  176,  163,    0,  155,  154,
        0,    0,  134,    0,    0,    0,  151,  100,    0,  463,
      272,  277,  282,  287,  289,  294,  299,  304,   72
    } ;

static const flex_int16_t yy_def[340] =
    {   0,
      330,    1,  331,  331,  330,  330,  330,  330,  330,  332,
      333,  330,  330,  334,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      335,  330,  330,  330,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  330,
      330,  330,  330,  336,  337,  336,  330,  330,  332,  330,
      332,  333,  330,  330,  330,  330,  334,  334,  330,  330,
      330,  330,  330,  330,  330,  338,  330,  330,  330,  330,
      339,  330,  330,  330,  330,  330,  330,  330,  335,  330,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  330,  330,  336,  337,
      336,  330,  330,  330,  330,  338,  330,  330,  330,  330,
      330,  330,  339,  330,  330,  330,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  330,  330,
      330,  330,  330,  330,  330,  330,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  330,  330,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,    0,
      330,  330,  330,  330,  330,  330,  330,  330,  330
    } ;

static const flex_int16_t yy_nxt[527] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   31,   31,
       31,   32,    6,   33,   34,   35,   36,   37,   38,   39,
       40,   31,   31,   41,   31,   42,   31,   43,   31,   44,
       45,   46,   47,   31,   48,   49,   31,   31,   31,   50,
       51,   52,   53,    8,    8,   60,   55,   55,   65,   70,
       74,   74,   72,   84,   85,  143,   75,   56,   56,   71,
       73,   76,   78,   66,   82,   82,   78,   77,   79,   79,
       87,   88,   95,   61,   80,   92,  101,   93,   80,   96,

       99,   81,   97,  103,   94,   98,   80,  102,  107,  100,
       80,  104,  127,  105,  108,  109,  106,  114,   63,   60,
       57,   57,   57,   57,  111,  123,  118,   81,  112,  132,
      145,  146,  115,  124,  330,  116,  119,  120,  329,  121,
       67,  122,  113,  151,  152,   74,   74,   61,  138,  138,
      128,  165,  166,   68,  133,  134,  133,  139,  140,  139,
       78,   63,   79,   79,  142,  142,  133,  134,  133,  139,
      140,  139,   80,  172,  141,   62,  141,   62,  173,  142,
      142,  181,  183,   78,   80,   82,   82,  186,  182,  187,
      328,  189,  327,  189,  326,   80,  190,  190,  205,  206,

      184,  138,  138,  193,  185,  193,  325,   80,  194,  194,
      191,  192,  191,  190,  190,  324,  142,  142,   62,  323,
       62,  322,  191,  192,  191,  195,  214,  195,  238,  215,
      238,  190,  190,  239,  239,  194,  194,  195,  321,  195,
      133,  320,  133,  319,  194,  194,  239,  239,  239,  239,
      318,  317,  133,  139,  133,  139,  316,  191,  315,  191,
      314,  313,  312,  311,  310,  139,  309,  139,  308,  191,
      307,  191,   54,   54,   54,   54,   54,   59,   59,   59,
       59,   59,   62,   62,   62,   62,   62,   67,   67,  306,
       67,   67,   89,   89,  129,  305,  129,  129,  129,  130,

      130,  130,  130,  130,  136,  136,  136,  136,  136,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  213,  212,  211,  210,

      209,  208,  207,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  137,  188,  180,  179,  178,  177,  176,  175,
      174,  171,  170,  169,  168,  167,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  150,  149,
      148,  147,  144,  137,  135,   63,  330,  131,  126,  125,
      117,  110,   91,   90,   86,   83,   69,   68,   64,   63,
       58,  330,    5,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330
    } ;

static const flex_int16_t yy_chk[527] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   10,    3,    4,   13,   18,
       21,   21,   20,   27,   27,  339,   22,    3,    4,   18,
       20,   22,   24,   13,   24,   24,   23,   22,   23,   23,
       29,   29,   37,   10,   24,   36,   39,   36,   23,   37,

       38,   23,   37,   40,   36,   37,   24,   39,   41,   38,
       23,   40,   51,   40,   41,   41,   40,   44,   55,   59,
        3,    4,    3,    4,   43,   47,   46,   23,   43,   67,
       88,   88,   44,   47,   68,   44,   46,   46,  328,   46,
       68,   46,   43,   95,   95,   74,   74,   59,   78,   78,
       51,  109,  109,   67,   74,   74,   74,   78,   78,   78,
       79,  130,   79,   79,  141,  141,   74,   74,   74,   78,
       78,   78,   79,  115,   80,   55,   80,   55,  115,   80,
       80,  123,  124,   82,   79,   82,   82,  125,  123,  125,
      327,  134,  323,  134,  320,   82,  134,  134,  155,  155,

      124,  138,  138,  140,  124,  140,  319,   82,  140,  140,
      138,  138,  138,  189,  189,  317,  142,  142,  130,  316,
      130,  315,  138,  138,  138,  142,  164,  142,  192,  164,
      192,  190,  190,  192,  192,  193,  193,  142,  314,  142,
      190,  313,  190,  312,  194,  194,  238,  238,  239,  239,
      309,  308,  190,  194,  190,  194,  307,  239,  306,  239,
      303,  302,  301,  297,  295,  194,  294,  194,  293,  239,
      291,  239,  331,  331,  331,  331,  331,  332,  332,  332,
      332,  332,  333,  333,  333,  333,  333,  334,  334,  286,
      334,  334,  335,  335,  336,  285,  336,  336,  336,  337,

      337,  337,  337,  337,  338,  338,  338,  338,  338,  284,
      282,  281,  279,  278,  277,  275,  274,  273,  272,  270,
      269,  268,  267,  266,  264,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  251,  249,  248,  247,  246,
      241,  240,  237,  236,  233,  232,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  219,  217,  216,  215,
      214,  213,  212,  211,  210,  208,  207,  206,  205,  204,
      202,  199,  198,  197,  188,  187,  186,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  168,  167,  166,  165,  162,  161,  160,  159,

      158,  157,  156,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  136,  126,  122,  121,  120,  119,  118,  117,
      116,  114,  113,  112,  111,  110,  108,  106,  105,  104,
      103,  102,  101,  100,   99,   98,   97,   96,   94,   93,
       92,   91,   84,   76,   75,   62,   61,   56,   49,   48,
       45,   42,   35,   34,   28,   25,   17,   14,   12,   11,
        9,    5,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
#line 8 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
/*
 * java.l
 *
 *  Copyright by the COMMONWEALTH SCIENTIFIC AND INDUSTRIAL RESEARCH
 *  ORGANISATION (CSIRO), Australia.
 *  All rights reserved.
 *
 *  This file is part of ADT.  The full ADT copyright notice, including
 *  terms governing use, modification, and redistribution, is contained in
 *  the file COPYING. COPYING can be found at the root of the source code
 *  distribution tree;
 *
 * lex input file for java scanner with limited java extensions
 *
 * note that we include trailing comments in the IDENTIFIER token so that we can
 * extract Marks array size comments on variable declarations
 */


#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "lexer.h"
#include "adtutils.hpp"


#if defined(_MSC_VER)
  #include <io.h>

  #define isatty _isatty

  #pragma warning(disable : 4996)
#else
  #include <unistd.h>
#endif


#define TOKEN_KEYWORD 0
#define TOKEN_NUMBER  1
#define TOKEN_TEXT    2


#define YYSTYPE   javaType


#include "java_y.h"


int         yyJavadebug               = 0;

int         adtJava_nError            = 0;
int         adtJava_nLineNumber       = 1;
const char* adtJava_pFileName         = "";
int         adtJava_nBlockDepth       = 0;
void*       adtJava_pJavaContext      = 0;
int         adtJava_nIfDefSP          = 0;
int         adtJava_nIfDefStack[64]   = {0};
int         adtJava_nIfDefCodeActive  = 1;
char        adtJava_sLastLine[512]    = {0};
int         adtJava_nLastLineCount    = 0;


static int input();


void yyJava_appendToLastLine(const char* pText)
{
  int         nLength     = strlen(pText);
  int         nMaxLength  = (sizeof(adtJava_sLastLine) / sizeof(*adtJava_sLastLine)) - 1;
  const char* pTextChar   = pText;

  while (*pTextChar != 0)
  {
    if (adtJava_nLastLineCount < nMaxLength)
    {
      adtJava_sLastLine[adtJava_nLastLineCount] = *pTextChar;
      adtJava_nLastLineCount++;
    }
    else
    {
      break;
    }

    pTextChar++;
  }

  adtJava_sLastLine[adtJava_nLastLineCount] = 0;
}


void yyJava_resetLastLine()
{
  adtJava_nLastLineCount                   = 0;
  adtJava_sLastLine[adtJava_nLastLineCount] = 0;
}


void yyJava_ifDefUpdateActive()
{
  int cn;
  int nActive = 1;

  for (cn = 1 ; cn <= adtJava_nIfDefSP ; cn++)
  {
    nActive *= adtJava_nIfDefStack[cn];
  }

  adtJava_nIfDefCodeActive = nActive;
}


void yyJava_beginIfDef(int nOn)
{
  if (adtJava_nIfDefSP < 63)
  {
    adtJava_nIfDefSP++;
    adtJava_nIfDefStack[adtJava_nIfDefSP] = (nOn != 0) ? 1 : 0;

    yyJava_ifDefUpdateActive();
  }
}


void yyJava_elseIfDef()
{
  adtJava_nIfDefStack[adtJava_nIfDefSP] = (adtJava_nIfDefStack[adtJava_nIfDefSP] != 0) ? 0 : 1;
  yyJava_ifDefUpdateActive();
}


void yyJava_endIfDef()
{
  if (adtJava_nIfDefSP > 0)
  {
    adtJava_nIfDefSP--;
    yyJava_ifDefUpdateActive();
  }
}


void yyJava_endParse(void)
{
  yy_flush_buffer(YY_CURRENT_BUFFER);
  yyJava_resetLastLine();

  adtJava_nLineNumber     = 1;
  adtJava_nBlockDepth     = 0;
  adtJava_nIfDefSP        = 0;
}


void yyJava_releaseBuffer(void)
{
  yy_delete_buffer(YY_CURRENT_BUFFER);

  if (adtJava_nError != 0)
  {
    adtJava_releaseRoot();
  }
}


int yyJava_lineNumber(void)
{
  return (adtJava_nLineNumber);
}


const char* yyJava_fileName(void)
{
  return (adtJava_pFileName);
}


void yyJava_resetLineNumber(const char* pFileName)
{
  adtJava_nError      = 0;
  adtJava_nLineNumber = 1;
  adtJava_pFileName   = "";

  if (pFileName != 0)
  {
    adtJava_pFileName = pFileName;
  }
}


int yyJava_error(void)
{
  return (adtJava_nError);
}


void yyJavaerror(char const* sErrorMessage)
{
  printf("CPP COMPILE ERROR on line %d in file %s : %s\n", adtJava_nLineNumber, adtJava_pFileName, sErrorMessage);
  printf("Context : %s\n", adtJava_sLastLine);

  adtJava_LogFlush(adtJava_pJavaContext);

  adtJava_nError = 1;
}


int dispatchToken(void* pContext, YYSTYPE* p_yylval, const char* pTokenText, int nType, int nToken)
{
  if (p_yylval != 0)
  {
    p_yylval->pContext    = pContext;
    p_yylval->dValue      = 0.0;
    p_yylval->nValue      = 0;
    p_yylval->sValue      = 0;
    p_yylval->nBlockDepth = adtJava_nBlockDepth;

    switch (nType)
    {
      case TOKEN_KEYWORD:
      case TOKEN_TEXT:
      {
        switch (nToken)
        {
          case EMBEDDED_COMMANDS:
          {
            adtJava_ParseCommandBlock(pContext, pTokenText);
            /* fall through */
          }

          case SINGLELINE_COMMENT:
          case MULTILINE_COMMENT:
          {
            adtJava_AppendComment(pContext, pTokenText, adtJava_pFileName, adtJava_nLineNumber);
            break;
          }

          default:
          {
            p_yylval->sValue = adtJava_AllocString(pContext, pTokenText, 1);
            break;
          }
        }
        break;
      }

      case TOKEN_NUMBER:
      {
        p_yylval->sValue = adtJava_AllocString(pContext, pTokenText, 0);
        p_yylval->dValue = atof(pTokenText);
        break;
      }

      default:
      {
        break;
      }
    }

    adtJava_LogText(pContext, pTokenText, adtJava_nLineNumber);
    yyJava_appendToLastLine(pTokenText);
  }

  return (nToken);
}


void commenteof()
{
  printf ("unexpected EOF inside comment at line %d\n", adtJava_nLineNumber);
  AdtExit(1);
}


char* growBuffer(char* pBuffer, int* pnSize, int nGrowSize)
{
  char* pOldBuffer  = pBuffer;
  int   nNewSize    = *pnSize + nGrowSize;

  pBuffer = (char*)malloc(nNewSize * sizeof(char));

  memset(pBuffer, 0, nNewSize * sizeof(char));
  memcpy(pBuffer, pOldBuffer, (*pnSize) * sizeof(char));
  free(pOldBuffer);

  *pnSize = nNewSize;

  return (pBuffer);
}


char* mallocScanComment(const char* pClosingBrace, int nToUpper)
{
  int         nGrowSize     = 1024;
  int         nSize         = nGrowSize;
  char*       pBuffer       = (char*)malloc(nSize * sizeof(char));
  char        nChar         = 0;
  int         nCharCount    = 0;
  const char* pMatch        = pClosingBrace;
  const char* pToken        = yytext;
  int         bMatched      = 0;

  memset(pBuffer, 0, nSize * sizeof(char));

  while (*pToken != '\0')
  {
    if (nCharCount >= nSize - 1)
    {
      pBuffer = growBuffer(pBuffer, &nSize, nGrowSize);
    }

    pBuffer[nCharCount] = (nToUpper == 0) ? *pToken : toupper(*pToken);
    nCharCount++;
    pToken++;
  }

  for (nChar = input() ; nChar != 0 ; nChar = input())
  {
    if (nCharCount >= nSize - 1)
    {
      pBuffer = growBuffer(pBuffer, &nSize, nGrowSize);
    }

    pBuffer[nCharCount] = (nToUpper == 0) ? nChar : toupper(nChar);
    nCharCount++;

    if (nChar == '\n')
    {
      yyJava_resetLastLine();
      adtJava_nLineNumber++;
    }

    if (nChar == *pMatch)
    {
      pMatch++;

      if (*pMatch == '\0')
      {
        bMatched = 1;
        break;
      }
    }
    else
    {
      pMatch = pClosingBrace;
    }
  }

  if (!bMatched)
  {
    commenteof();
  }

  return (pBuffer);
}


#line 1024 "..\\src\\java_l.c"

#line 1026 "..\\src\\java_l.c"

#define INITIAL 0
#define NOT_AD_CODE 1

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 369 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"

#line 1238 "..\\src\\java_l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 331 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 463 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 370 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT, SINGLELINE_COMMENT);
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 371 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  const char* pChar = adtJava_AllocString(adtJava_pJavaContext, yytext, 0);

                                  dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT, SINGLELINE_COMMENT);

                                  while (*pChar != '\0')
                                  {
                                    pChar = adtParse_nextWord(pChar, 0, 1);

                                    if (adtParse_matchWord(&pChar, "#ifdef", 1))
                                    {
                                      pChar = adtParse_nextWord(pChar, 0, 1);

                                      if (adtParse_matchWord(&pChar, "AD", 1))
                                      {
                                        yyJava_beginIfDef(1);
                                      }
                                      else
                                      {
                                        yyJava_beginIfDef(0);
                                      }
                                    }
                                    else if (adtParse_matchWord(&pChar, "#ifndef", 1))
                                    {
                                      pChar = adtParse_nextWord(pChar, 0, 1);

                                      if (adtParse_matchWord(&pChar, "AD", 1))
                                      {
                                        yyJava_beginIfDef(0);
                                      }
                                      else
                                      {
                                        yyJava_beginIfDef(1);
                                      }
                                    }
                                    else if (adtParse_matchWord(&pChar, "#else", 1))
                                    {
                                      yyJava_elseIfDef();
                                    }
                                    else if (adtParse_matchWord(&pChar, "#endif", 1))
                                    {
                                      yyJava_endIfDef();
                                    }
                                    else
                                    {
                                      pChar = adtParse_nextLine(pChar, 0);
                                    }
                                  }

                                  if (adtJava_nIfDefCodeActive != 0)
                                  {
                                    BEGIN(INITIAL);
                                  }
                                  else
                                  {
                                    BEGIN(NOT_AD_CODE);
                                  }
                                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 429 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  char* pComment = mallocScanComment("*/", 0);

                                  if (pComment != 0)
                                  {
                                    dispatchToken(adtJava_pJavaContext, &yylval, pComment, TOKEN_TEXT, EMBEDDED_COMMANDS);
                                    free(pComment);
                                  }
                                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 439 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  char* pComment = mallocScanComment("*/", 0);

                                  if (pComment != 0)
                                  {
                                    dispatchToken(adtJava_pJavaContext, &yylval, pComment, TOKEN_TEXT, MULTILINE_COMMENT);
                                    free(pComment);
                                  }
                                }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 449 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT, SINGLELINE_COMMENT);
                                  yyJava_resetLastLine();
                                  adtJava_nLineNumber++;
                                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 455 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, ABSTRACT));
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 456 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, BOOL));
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 457 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, BOOLEAN));
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 458 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, BREAK));
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 459 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, BYTE));
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 460 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, CASE));
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 461 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, CATCH));
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 462 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, CHAR));
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 463 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, CLASS));
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 464 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, CONST));
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 465 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, CONTINUE));
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 466 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, DEFAULT));
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 467 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, DO));
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 468 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, DOUBLE));
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 469 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, ELSE));
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 470 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, EXTENDS));
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 471 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, FINALLY));
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 472 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, FINAL));
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 473 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, FLOAT));
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 474 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, FOR));
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 475 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, IF));
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 476 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, IMPLEMENTS));
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 477 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, IMPORT));
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 478 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, INTERFACE));
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 479 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, INSTANCEOF));
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 480 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, INT));
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 481 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LONG));
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 482 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, NATIVE));
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 483 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, NEW));
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 484 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, PACKAGE));
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 485 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, PUBLIC));
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 486 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, PRIVATE));
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 487 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, PROTECTED));
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 488 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, RETURN));
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 489 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SHORT));
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 490 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, STATIC));
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 491 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SUPER));
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 492 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SWITCH));
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 493 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SYNCHRONIZED));
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 494 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, THIS));
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 495 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, THROW));
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 496 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, THROWS));
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 497 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, TRANSIENT));
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 498 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, TRY));
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 499 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, VOID));
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 500 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, VOLATILE));
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 501 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, WHILE));
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 502 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, BOOLEANLITERAL));
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 503 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, BOOLEANLITERAL));
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 504 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, NULLLITERAL));
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 505 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SHR_EQUALS));
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 506 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SAR_EQUALS));
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 507 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SAL_EQUALS));
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 508 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, PLUS_EQUALS));
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 509 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, MINUS_EQUALS));
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 510 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, TIMES_EQUALS));
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 511 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, DIV_EQUALS));
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 512 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, MOD_EQUALS));
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 513 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, AND_EQUALS));
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 514 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, XOR_EQUALS));
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 515 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, OR_EQUALS));
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 516 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SHR));
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 517 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SAR));
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 518 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SAL));
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 519 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, INCR));
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 520 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, DECR));
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 521 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LAND));
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 522 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LOR));
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 523 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LTE));
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 524 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, GTE));
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 525 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, EQ));
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 526 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, NE));
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 527 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SEMICOLON));
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 528 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  int nReturn = dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LCBRACKET);

                                  adtJava_nBlockDepth++;
                                  return (nReturn);
                                }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 534 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  adtJava_nBlockDepth--;
                                  return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, RCBRACKET));
                                }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 538 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, COMMA));
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 539 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, COLON));
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 540 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, EQUALS));
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 541 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LBRACKET));
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 542 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, RBRACKET));
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 543 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LSQRBRACKET));
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 544 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, RSQRBRACKET));
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 545 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, PERIOD));
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 546 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, AND));
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 547 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LNOT));
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 548 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, NOT));
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 549 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, MINUS));
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 550 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, PLUS));
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 551 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, MULTIPLY));
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 552 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, DIV));
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 553 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, MOD));
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 554 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, LT));
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 555 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, GT));
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 556 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, XOR));
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 557 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, OR));
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 558 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, QUESTION));
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 559 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, SCOPE));
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 560 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, IDENTIFIER));
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 561 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, INTEGERLITERAL));
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 562 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, INTEGERLITERAL));
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 563 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, INTEGERLITERAL));
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 564 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, FLOATINGPOINTLITERAL));
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 565 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, FLOATINGPOINTLITERAL));
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 566 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_KEYWORD, FLOATINGPOINTLITERAL));
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 567 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT,    CHARACTERLITERAL));
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 568 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
return (dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT,    STRINGLITERAL));
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 569 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT, -1);
                                  yyJava_resetLastLine();
                                  adtJava_nLineNumber++;
                                }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 574 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT, -1);
                                }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 577 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
{
                                  dispatchToken(adtJava_pJavaContext, &yylval, yytext, TOKEN_TEXT, -1);
                                  printf("'%c' (0x%x): illegal character at line %d\n", yytext[0], yytext[0], adtJava_nLineNumber);
                                }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 582 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"
ECHO;
	YY_BREAK
#line 1969 "..\\src\\java_l.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NOT_AD_CODE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 331 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 331 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 330);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 582 "C:\\cygwin\\usr\\src\\adt\\src\\java_l.l"



int yywrap()
{
  return (1);
}

